### ISSUE TITLE
Endless loading upon launching desktop app

### ISSUE THREAD

**Issue by CodeShakingSheep** [KRTirtho/spotube#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening Spotube it just loads endlessly. I haven't even logged in to Spotify.

### Expected Behavior

Spotube should finish loading and be usable.

### Steps to reproduce

1. Just launch the app.

### Operating System

Linux Ubuntu derivative (Zorin 17 Pro)

### Spotube version

3.4.0

### Installation source

Flathub (Flatpak)

### Additional information

Here are relevant logs.
```
------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-01-05 23:57:19.060578

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 9638ecc236204733b0cb7c66ac7682d7

------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 27
packageName: spotube

---------- ERROR ----------
FormatException: Invalid date format
2024-01-03 23:02:58.9674---

------- STACK TRACE -------
#0      DateTime.parse (dart:core/date_time.dart:358)
#1      LogsPage.parseLogs.<anonymous closure>.<anonymous closure> (package:spotube/pages/settings/logs.dart:32)
#2      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#4      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#5      Iterable.join (dart:core/iterable.dart:460)
#6      LogsPage.parseLogs.<anonymous closure> (package:spotube/pages/settings/logs.dart:40)
#7      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#8      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#9      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#10     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#12     new List.of (dart:core-patch/array_patch.dart:39)
#13     Iterable.toList (dart:core/iterable.dart:497)
#14     LogsPage.parseLogs (package:spotube/pages/settings/logs.dart:49)
#15     LogsPage.build.<anonymous closure>.<anonymous closure> (package:spotube/pages/settings/logs.dart:66)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```

This is how it looks like
![image](https://github.com/KRTirtho/spotube/assets/19874562/d176be52-2c23-4873-9f1f-80d8fceed2a6)

**Comment by abhinavanand-fed** [comment]
You should try changing the DNS settings for the connected network.

**Comment by KRTirtho** [comment]
Unfortunately, due to recent popularity rise and user increase all the Spotify public clientIds and clientSecrets are in heavy usage, thus throwing API quota exceeded error every time. You can log in with your Spotify account, and it'll start to work.

**Comment by CodeShakingSheep** [comment]
Thanks for your fast reply @KRTirtho . I logged in with my Spotify account and it works now. Awesome! :) For the sake of usability I would suggest to add a message about that if loading times out.

**Comment by Zedisverydead** [comment]
Could you be more specific? My Google TV Chromecast doesn't let me reach the log in option, just freezes at start and remote doen't respond

**Comment by KRTirtho** [comment]
Android TV support isn't there yet. The app opens but Focus traversal and remote button based navigation doesn't work as underlying Flutter framework still doesn't support it

**Comment by lemayian-tech** [comment]
thanks KRTirtho! i absolutely love the app

**Comment by Zedisverydead** [comment]
Thank you for your answer and your awesome work. Just dreaming about an android TV versión, It looks amazing in a big screen too. Fantastic app KRThirtho. Thank you!

**Comment by khlsvr** [comment]
I have a related problem in that after logging in and everything working fine, then the next day or two when I come back, the problem comes back. The settings page has "log out" button which by clicking I can log out and then login back in by going through the tedious process of obtaining the sp_dc and then it works again.

How can I stay logged in properly without having to go through the sp_dc process so often?

**Comment by numfin** [comment]
Unable to login in android app too. 403

**Comment by Zedisverydead** [comment]
Maybe a bit stupid, I didn't try yet but thinking about connecting a bluetooth keynoard+mouse to Chromecast and log in using them because just remote is not responding. Once you logged in maybe everything works fine in Google TV...
