### ISSUE TITLE
Can't play music

### ISSUE THREAD

**Issue by chen-junl** [KRTirtho/spotube#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I search for Jay's songs and click play, the icon keeps loading and the music cannot be played.

![image](https://github.com/KRTirtho/spotube/assets/38237837/62db235a-fa90-4092-a025-50350671b92e)

![image](https://github.com/KRTirtho/spotube/assets/38237837/b31ba33c-5e66-463a-8969-bcaf88d55f8b)

1. 

### Expected Behavior

 play music

### Steps to reproduce

When I search for Jay's songs and click play, the icon keeps loading and the music cannot be played.

![image](https://github.com/KRTirtho/spotube/assets/38237837/62db235a-fa90-4092-a025-50350671b92e)

![image](https://github.com/KRTirtho/spotube/assets/38237837/b31ba33c-5e66-463a-8969-bcaf88d55f8b)

1. 

### Operating System

Windows 11 22631.3085

### Spotube version

v3.4.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by chen-junl** [comment]
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
computerName: DESKTOP-JLRLRGU
numberOfCores: 8
systemMemoryInMegabytes: 16384
------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
FormatException: Unexpected character (at character 1)
Too many requests
^
------- STACK TRACE -------
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleErrors (package:spotify/src/spotify_base.dart:232)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#10     PlaylistQueries.featured.<anonymous closure> (package:spotube/services/queries/playlist.dart:255)
<asynchronous suspension>
#11     _AsyncCompleter.complete (dart:async/future_impl.dart:41)
<asynchronous suspension>
#12     Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:17)
<asynchronous suspension>
#13     CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by KRTirtho** [comment]
It seems to be working fine.

<img width="1206" alt="image" src="https://github.com/KRTirtho/spotube/assets/61944859/e911ca0e-1bc1-49a9-8a5c-310924f7b50a">
