### ISSUE TITLE
closes randomly

### ISSUE THREAD

**Issue by Soyasi** [KRTirtho/spotube#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

closes randomly

### Expected Behavior

no closes randomly

### Steps to reproduce

closes randomly

### Operating System

linux

### Spotube version

3.4.1

### Installation source

GitHub Releases (Binary)

### Additional information

============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-01-28 11:50:55.718078

------- DEVICE INFO -------
name: openSUSE Tumbleweed
version: null
id: opensuse-tumbleweed
idLike: [opensuse, suse]
versionCodename: null
versionId: 20240126
prettyName: openSUSE Tumbleweed
buildId: null
variant: null
variantId: null
machineId: 5c30331d485b4f4b81107ac9bd321f6c

------- APP INFO -------
environment: release
version: 3.4.1
appName: spotube
buildNumber: 28
packageName: spotube

---------- ERROR ----------
FormatException: Unexpected character (at character 1)
Too many requests
^

------- STACK TRACE -------
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleErrors (package:spotify/src/spotify_base.dart:232)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#10     PlaylistQueries.featured.<anonymous closure> (package:spotube/services/queries/playlist.dart:255)
<asynchronous suspension>
#11     _AsyncCompleter.complete (dart:async/future_impl.dart:41)
<asynchronous suspension>
#12     Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:17)
<asynchronous suspension>
#13     CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
soyasi2@soyasi2:~>spotube

(process:4752): GLib-GObject-CRITICAL **: 11:58:39.341: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'

(spotube:4752): Gdk-CRITICAL **: 11:58:39.378: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: Configure AudioServiceLinux.
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /usr/share/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /usr/share/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call SetContextMenu
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
flutter: setQueue() has not been implemented.
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /usr/share/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /usr/share/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /usr/share/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
method call SetContextMenu
method call SetContextMenu

(spotube:4752): GLib-CRITICAL **: 11:58:44.113: g_variant_new_string: assertion 'string != NULL' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_new_variant: assertion 'value != NULL' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_get_type: assertion 'value != NULL' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_builder_add_value: assertion '!GVSB(builder)->expected_type || g_variant_is_of_type (value, GVSB(builder)->expected_type)' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_builder_end: assertion 'GVSB(builder)->offset >= GVSB(builder)->min_items' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_get_type: assertion 'value != NULL' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(spotube:4752): GLib-CRITICAL **: 11:58:44.114: g_variant_builder_add_value: assertion '!GVSB(builder)->expected_type || g_variant_is_of_type (value, GVSB(builder)->expected_type)' failed
flutter: MenuItem select menuId:5 menuItemId:7

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Name your Linux distribution with Hardware specs please

**Comment by Soyasi** [comment]
```
inxi -Fxz
System:
  Kernel: 6.7.1-2-default arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
    Desktop: KDE Plasma v: 5.27.10 Distro: openSUSE Tumbleweed 20240129
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: N/A
  Mobo: ASUSTeK model: TUF GAMING X570-PRO (WI-FI) v: Rev X.0x
    serial: <filter> UEFI: American Megatrends v: 5003 date: 10/07/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP arch: Zen+
    rev: 2 cache: L1: 768 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 2543 high: 3700 min/max: 2200/3700 boost: enabled cores:
    1: 2200 2: 3700 3: 2200 4: 2200 5: 2200 6: 3700 7: 3700 8: 2200 9: 2200
    10: 2200 11: 2200 12: 3200 13: 2200 14: 2200 15: 2200 16: 2200
    bogomips: 118218
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Micro-Star MSI driver: amdgpu v: kernel arch: GCN-4 bus-ID: 0a:00.0
    temp: 57.0 C
  Device-2: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
    bus-ID: 1-2:3
  Device-3: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
    bus-ID: 5-4:3
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: radeonsi gpu: amdgpu
    resolution: 3840x2160~64Hz
  API: EGL v: 1.5 drivers: radeonsi,swrast platforms:
    active: x11,surfaceless,device inactive: gbm,wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.4 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 580 Series (radeonsi polaris10
    LLVM 17.0.6 DRM 3.56 6.7.1-2-default)
  API: Vulkan v: 1.3.275 drivers: N/A surfaces: xcb,xlib devices: 1
Audio:
  Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
    vendor: Micro-Star MSI driver: snd_hda_intel v: kernel bus-ID: 0a:00.1
  Device-2: AMD Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel
    v: kernel bus-ID: 0c:00.3
  Device-3: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
    bus-ID: 1-2:3
  Device-4: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
    bus-ID: 5-4:3
  API: ALSA v: k6.7.1-2-default status: kernel-api
  Server-1: PipeWire v: 1.0.1 status: active
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 05:00.0
  IF: wlp5s0 state: up mac: <filter>
  Device-2: Intel Ethernet I225-V vendor: ASUSTeK driver: igc v: kernel
    port: N/A bus-ID: 06:00.0
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth driver: btusb v: 0.8 type: USB bus-ID: 1-4:7
  Report: btmgmt ID: hci0 rfk-id: 3 state: up address: <filter> bt-v: 5.2
    lmp-v: 11
Drives:
  Local Storage: total: 1.93 TiB used: 48.73 GiB (2.5%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS100T1X0E-00AFY0
    size: 931.51 GiB temp: 45.9 C
  ID-2: /dev/nvme1n1 vendor: Western Digital model: WD Red SN700 250GB
    size: 232.89 GiB temp: 41.9 C
  ID-3: /dev/sda vendor: Samsung model: SSD 860 EVO M.2 250GB
    size: 232.89 GiB
  ID-4: /dev/sdb vendor: Fujitsu model: MHW2120BH size: 111.79 GiB
  ID-5: /dev/sdc vendor: Western Digital model: WDS500G1B0B-00AS40
    size: 465.76 GiB
Partition:
  ID-1: / size: 165.09 GiB used: 26.08 GiB (15.8%) fs: btrfs dev: /dev/sdc2
  ID-2: /boot/efi size: 511 MiB used: 5.9 MiB (1.1%) fs: vfat dev: /dev/sdc1
  ID-3: /home size: 200.79 GiB used: 22.65 GiB (11.3%) fs: xfs
    dev: /dev/nvme1n1p2
  ID-4: /opt size: 165.09 GiB used: 26.08 GiB (15.8%) fs: btrfs
    dev: /dev/sdc2
  ID-5: /var size: 165.09 GiB used: 26.08 GiB (15.8%) fs: btrfs
    dev: /dev/sdc2
Swap:
  ID-1: swap-1 type: partition size: 32 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme1n1p1
Sensors:
  System Temperatures: cpu: 45.5 C mobo: 38.0 C gpu: amdgpu temp: 57.0 C
  Fan Speeds (rpm): fan-1: 0 fan-2: 980 fan-3: 801 fan-4: 0 fan-5: 2678
    fan-6: 0 fan-7: 2184 gpu: amdgpu fan: 1317
Info:
  Processes: 458 Uptime: 0h 27m Memory: total: 64 GiB available: 62.7 GiB
  used: 7.38 GiB (11.8%) Init: systemd Compilers: gcc: 13.2.1 Packages: N/A
  note: see --rpm Shell: Bash v: 5.2.26 inxi: 3.3.31
```
