### ISSUE TITLE
🔈 The musics play, but with no sound. 

### ISSUE THREAD

**Issue by FelipeFTN** [KRTirtho/spotube#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The track is playing, but with no sound at all.
I'm using **pulseaudio**, but I also have **pipewire** installed in any case...

### Expected Behavior

The track follows, and the music plays correctly **with sound**.

### Steps to reproduce

1. I installed the app through AUR (spotube - not the bin)
2. I Opened the app
3. I did all the authentication steps with Spotify's cookie
4. When I play some music it starts counting the timer, but I have no sound.

### Operating System

Linux Manjaro

### Spotube version

v3.4.1-2

### Installation source

Arch User Repository (AUR)

### Additional information

Here are my logs:
```
============================== CATCHER 2 LOG ==============================
=------- DEVICE INFO -------
name: Manjaro Linux
version: null
id: manjaro
idLike: [arch]
versionCodename: Vulcan
versionId: 23.1.3
prettyName: Manjaro Linux
buildId: rolling
variant: null
variantId: null
machineId: 8302cba346cc4c1eb198ac9560754b07
------- APP INFO -------
environment: release
version: 3.4.1
appName: spotube
buildNumber: 28
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot retrieve length of file, path = 'imageUrl' (OS Error: No such 
---------- ERROR ----------
OAuth authorization error (inv#0      _check
------- STACK TRACE -------
#0      _handleErrorResponse (package:oauth2/src/handle_access_token_response.dart:155)
#1      handleAccessTokenResponse (package:oauth2/src/handle_access_token_response.dart:41)
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:74)
<asynchronous suspension>
#3      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:179)
<asynchronous suspension>
#4      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#5      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#6      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:273)
<asynchronous suspension>
#7      ArtistQueries.followedByMeAll.<anonymous closure> (package:spotube/services/queries/artist.dart:52)
<asynchronous suspension>
#8      _AsyncCompleter.complete (dart:async/future_impl.dart:41)
<asynchronous suspension>
#9      Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:17)
<asynchronous suspension>
#10     CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
<asynchronous suspension>
------- CUSTOM INFO -------
```
I got this errors on my terminal too:
```
(process:5080): GLib-GObject-CRITICAL **: 23:21:11.943: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTir
tho.Spotube'
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:11.798460
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:11.798460
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:11.862425
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:16.875766
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:16.875766
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:16.875766
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:21.953064
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:21.953064
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:21.953064
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:26.966470
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:27.030403
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:27.030403
```

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Can you check if `mpv` works (plays with sound)?

```bash
$ mpv <any-music-track>.m4a
```

**Comment by FelipeFTN** [comment]
Heyy @KRTirtho! 
Yes, mpv is working just fine! :tada:

**Comment by FelipeFTN** [comment]
Hello Guys! I just found a way to solve the issue temporarily! :tada:
Looks like restarting the pulseaudio with `pulseaudio -k` magically makes the audio works again! :rocket:

I don't know why this happens, but just works, maybe some debug on it, or marking this as a known issue might work. 

Also, I found something about sample-rate in Manjaro that might help in the discovery somehow.
![image](https://github.com/KRTirtho/spotube/assets/80127749/d956d9f8-c092-4682-b6f8-cda43c5d8308)
> source: https://github.com/noisetorch/NoiseTorch/wiki/Troubleshooting

**Comment by FelipeFTN** [comment]
@FelipeFTN `mpv --audio-device=help`:
```
➜  ~ mpv --audio-device=help
List of detected audio devices:
  'auto' (Autoselect device)
  'pipewire' (Default (pipewire))
  'pipewire/alsa_output.pci-0000_00_1b.0.analog-stereo.5' (Built-in Audio Analog Stereo)
  'pulse/auto_null' (Dummy Output)
  'alsa' (Default (alsa))
  'alsa/lavrate' (Rate Converter Plugin Using Libav/FFmpeg Library)
  'alsa/samplerate' (Rate Converter Plugin Using Samplerate Library)
  'alsa/speexrate' (Rate Converter Plugin Using Speex Resampler)
  'alsa/jack' (JACK Audio Connection Kit)
  'alsa/oss' (Open Sound System)
  'alsa/pipewire' (PipeWire Sound Server)
  'alsa/speex' (Plugin using Speex DSP (resample, agc, denoise, echo, dereverb))
  'alsa/upmix' (Plugin for channel upmix (4,6,8))
  'alsa/vdownmix' (Plugin for channel downmix (stereo) with a simple spacialization)
  'alsa/sysdefault:CARD=PCH' (HDA Intel PCH, ALC662 rev1 Analog/Default Audio Device)
  'alsa/front:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/Front output / input)
  'alsa/surround21:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/2.1 Surround output to Front and Subwoofer speakers)
  'alsa/surround40:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/4.0 Surround output to Front and Rear speakers)
  'alsa/surround41:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/4.1 Surround output to Front, Rear and Subwoofer speakers)
  'alsa/surround50:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/5.0 Surround output to Front, Center and Rear speakers)
  'alsa/surround51:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/5.1 Surround output to Front, Center, Rear and Subwoofer speakers)
  'alsa/surround71:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Analog/7.1 Surround output to Front, Center, Side, Rear and Woofer speakers)
  'alsa/iec958:CARD=PCH,DEV=0' (HDA Intel PCH, ALC662 rev1 Digital/IEC958 (S/PDIF) Digital Audio Output)
  'alsa/usbstream:CARD=PCH' (HDA Intel PCH/USB Stream Output)
  'alsa/hdmi:CARD=HDMI,DEV=0' (HDA ATI HDMI, PMG30C900WFG/HDMI Audio Output)
  'alsa/hdmi:CARD=HDMI,DEV=1' (HDA ATI HDMI, HDMI 1/HDMI Audio Output)
  'alsa/hdmi:CARD=HDMI,DEV=2' (HDA ATI HDMI, HDMI 2/HDMI Audio Output)
  'alsa/hdmi:CARD=HDMI,DEV=3' (HDA ATI HDMI, HDMI 3/HDMI Audio Output)
  'alsa/hdmi:CARD=HDMI,DEV=4' (HDA ATI HDMI, HDMI 4/HDMI Audio Output)
  'alsa/hdmi:CARD=HDMI,DEV=5' (HDA ATI HDMI, HDMI 5/HDMI Audio Output)
  'alsa/usbstream:CARD=HDMI' (HDA ATI HDMI/USB Stream Output)
  'alsa/usbstream:CARD=Webcam' (C922 Pro Stream Webcam/USB Stream Output)
  'jack' (Default (jack))
  'openal' (Default (openal))
```

**Comment by olivier2** [comment]
I don't know much about how mpv works, but I would be curious to see the output of `mpv --audio-device=help` while other media apps (ideally other libmpv based apps) are running. Maybe even while playing a file with `mpv` directly.
