### ISSUE TITLE
The Windows app is using all network buffer space

### ISSUE THREAD

**Issue by skruglov2023** [KRTirtho/spotube#1269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At some point after running, background or foreground, my laptop's cache fills up and I'm no longer able to connect to any sites that haven't already been loaded, open any ssh or vpn, or anything. Requires a full app restart to clear issue temporarily. 

### Expected Behavior

My cache doesn't fill up and I'm not prevented from using the internet. 

### Steps to reproduce

Open the app
Start playing music
Can pause/play at any time
Continue using device until your device can't access anything

### Operating System

Windows 23H2 Build 22631.3155

### Spotube version

v3.4.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

This happens anywhere between a few times a day to a few times a week

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skruglov2023** [comment]
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
computerName: {laptop}
numberOfCores: 12
systemMemoryInMegabytes: 32768
------- APP INFO -------
environment: release
version: 3.4.1
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
ClientException with SocketException: Connection failed (OS Error: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
, errno = 10055), address = api.spotify.com, port = 443, uri=https://api.spotify.com/v1/browse/categories?country=US&locale=en&limit=20&offset=0
------- STACK TRACE -------
#0      IOClient.send (package:http/src/io_client.dart:119)
<asynchronous suspension>
#1      Client.send (package:oauth2/src/client.dart:114)
<asynchronous suspension>
#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#3      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:179)
<asynchronous suspension>
#4      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:212)
<asynchronous suspension>
#5      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:178)
<asynchronous suspension>
#6      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#7      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:171)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by Balou866** [comment]
Having the exact same problem as @skruglov2023.
I'm running Windows 23H2 Build 22631.3155 as well, on a desktop.
