### ISSUE TITLE
Flatpak failed to run on Linux Mint

### ISSUE THREAD

**Issue by sebastienserre** [KRTirtho/spotube#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here is the error I have in terminal:
```sebastien@Desktop:~$ flatpak run com.github.KRTirtho.Spotube

(process:2): GLib-GObject-CRITICAL **: 07:24:33.941: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
Gtk-Message: 07:24:33.943: Failed to load module "xapp-gtk3-module"

(spotube:2): Gdk-CRITICAL **: 07:24:33.963: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/sebastien/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.cache.infinite_queries.lock' (OS Error: Ressource temporairement non disponible, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      QueryClient.initialize (package:fl_query/src/core/client.dart:562)
<asynchronous suspension>
#6      main (package:spotube/main.dart:74)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/sebastien/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.cache.infinite_queries.lock' (OS Error: Ressource temporairement non disponible, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      QueryClient.initialize (package:fl_query/src/core/client.dart:562)
<asynchronous suspension>
#6      main (package:spotube/main.dart:74)
<asynchronous suspension>

```

### Expected Behavior

I expect Spotube launches :)

### Steps to reproduce

Install Spotube 
run the command `flatpak run com.github.KRTirtho.Spotube` 

### Operating System

Linux Mminit 21.3 Cinnamon

### Spotube version

c3.4.1

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by jojommeke** [comment]
same here in Ubuntu 22.04

**Comment by jojommeke** [comment]
```

F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak

(process:2): GLib-GObject-CRITICAL **: 14:23:48.341: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
Gtk-Message: 14:23:48.345: Failed to load module "xapp-gtk3-module"
Gtk-Message: 14:23:48.372: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:23:48.389: Failed to load module "canberra-gtk-module"

(spotube:2): Gdk-CRITICAL **: 14:23:48.469: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (spotube:2): WARNING **: 14:23:48.475: Failed to start Flutter renderer: Geen configuraties beschikbaar voor het gegeven beeldpuntformaat
package:media_kit_libs_linux registered.
log:
** (spotube:2): WARNING **: 14:23:48.476: gtk.dart: failed to call method: No engine to send to



```

**Comment by sebastienserre** [comment]
Unfortunatly, it dosn't work on my side;

**Comment by KRTirtho** [comment]
Does Spotube v3.8.0 run?
