### ISSUE TITLE
[iOS] Can’t download any songs 

### ISSUE THREAD

**Issue by OnellD27** [KRTirtho/spotube#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I go to the album and clicked on the song and can’t download it and it won’t let me even download the album.
![IMG_1330](https://github.com/KRTirtho/spotube/assets/77418010/bb337d3c-310a-48df-9885-713b2562f88d)
![IMG_1331](https://github.com/KRTirtho/spotube/assets/77418010/3e2eea32-ad5c-43f7-ac1f-5a4f1fa9bc00)
 

### Expected Behavior

It should download any song without any issues.

### Steps to reproduce

1. I opened the app
2. Then I searched for any album that I know and clicked on it 
3. Then I clicked on any song and clicked on download track.
4. And I tried with the album too.

### Operating System

iOS

### Spotube version

v3.5.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Awiskov** [comment]
I have also the same issue. Anybody did find a solution ? Pls need help

**Comment by mustard007** [comment]
> I have also the same issue. Anybody did find a solution ? Pls need help

Same here !

**Comment by tropicapic** [comment]
I have the same problem. Tested it for many different song. That’s the according exception from the logs:

`------- APP INFO -------
environment: release
version: 3.6.0
appName: Spotube
buildNumber: 30
packageName: oss.krtirtho.spotube.stable.2SA5C4ATLJ
---------- ERROR ----------
PathNotFoundException: Cannot copy file to '/var/mobile/Containers/Data/Application/00E9229B-5EDA-49A9-8EAE-F611A7346F5F/Downloads/Spotube/Magic Moment (feat. Chris de Sarandy) - Glockenbach, Chris de Sarandy.m4a', path = '/var/mobile/Containers/Data/Application/00E9229B-5EDA-49A9-8EAE-F611A7346F5F/Library/Caches/spotube-downloads/Magic Moment (feat. Chris de Sarandy) - Glockenbach, Chris de Sarandy.m4a.partial' (OS Error: No such file or directory, errno = 2)
------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:356)
<asynchronous suspension>
#2      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:143)
<asynchronous suspension>
#3      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:409)
<asynchronous suspension>
------- CUSTOM INFO ------- `

**Comment by aether-coder** [comment]
Can confirm the same issue from the screenshot in windows 11 latest update and Zorin OS 17.1 Lite

**Comment by slyrp** [comment]
still an issue ☹️
literally the only reason i got it on ios too--just to download songs

**Comment by CrazyM0nkey** [comment]
I hat the same issue with YT and Piped as source. But after changing to Jiosaavn downloads are working again.

**Comment by KRTirtho** [comment]
Fixed in 3.7.1

**Comment by OnellD27** [comment]
> Fixed in 3.7.1

Sorry, but it is still happening to me.

**Comment by Root-FTW** [comment]
> > Fixed in 3.7.1
> 
> Sorry, but it is still happening to me.

Same here, :(

![55bcbda9-02ba-44d0-8450-e3e9cefeff76](https://github.com/KRTirtho/spotube/assets/108767514/be804a4e-a4f5-4e8a-91ef-31bffbf58746)


LOG:

============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-06-06 12:32:35.431944

------- DEVICE INFO -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: E0FEA218-37D8-4D96-B779-573D954EF8D8
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
=====================version: 3.7.1
appName: Spotube
buildNumber: 32
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
type 'Null' is not a subtype of type 'String'

------- STACK TRACE -------
#0      AndroidBuildVersion._fromMap (package:device_info_plus/src/model/android_deutsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
environment: release
version: 3.7.1
appName: Spotube
buildNumber: 32
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
PlatformException(discoveryError, Bonsoir has encountered an error during discovery : -65555: NoAuth (error %s)., -65555, null)

------- STACK TRACE -------

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-06-06 12:33:38.140500

------- DEVICE INFO -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: E0FEA218-37D8-4D96-B779-573D954EF8D8
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
environment: release
version: 3.7.1
appName: Spotube
buildNumber: 32
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
PathAccessException: Creation failed, path = '/var/mobile/Containers/Data/Application/2CE3429A-735B-4D74-9C11-7833B0D76C73/Downloads' (OS Error: Operation not permitted, errno = 1)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109)
<asynchronous suspension>
#2      _Directory.create.<anonymous closure>.<anonymous closure> (dart:io/directory_impl.dart:99)
<asynchronous suspension>
#3      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:83)
<asynchronous suspension>
#4      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:411)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================

**Comment by Root-FTW** [comment]
Has anyone come up with a temporary solution?

**Comment by Haris-Muawiz-Khan** [comment]
I have been having the same OS Error regarding the PathAccessException as the app doesn't have access to the file system. I tried changing the file directory in settings but the app just "Crashes" and I get the above error in the logs. I checked the iPhone Privacy settings for file and folder permissions and it shows up and the switch is in an "ON" state. 

Any help regarding changing the download directory or giving permission to the app for files and folder access on iPhone would be appreciated. @KRTirtho

Thanks

**Comment by Root-FTW** [comment]
I think the author abandoned the project more than 2 months ago and there is no update or anything else :(

If you know of an alternative similar to this one it would be great if you could share it :(

**Comment by KRTirtho** [comment]
> I think the author abandoned the project more than 2 months ago and there is no update or anything else :(
> 
> If you know of an alternative similar to this one it would be great if you could share it :(

Nope. I did not quit. I was busy liberating my country.

**Comment by KRTirtho** [comment]
Try in 3.8.0. I've applied a fix

**Comment by aanks-s** [comment]
Hello @KRTirtho 
Just you to know that still doesn't work. 
I'm in version 3.8, tried today. Logs attached

![IMG_7D63820BEE02-1](https://github.com/user-attachments/assets/70b82110-6c67-4ce3-89f4-30bab9add89f)

**Comment by aanks-s** [comment]
Additional logs when trying to change the directory where the songs are supposed to be downloaded

[spotubelogs.txt](https://github.com/user-attachments/files/16603865/spotubelogs.txt)

**Comment by Haris-Muawiz-Khan** [comment]
Yeah same for me the issue still persists. The app does not ask for any permissions and in the logs it says operation not allowed.

Device: iPhone 15 Pro
iOS: 17.6.1

**Comment by hugomasson55** [comment]
> Hello @KRTirtho Just you to know that still doesn't work. I'm in version 3.8, tried today. Logs attached
> 
> ![IMG_7D63820BEE02-1](https://private-user-images.githubusercontent.com/176280127/357521522-70b82110-6c67-4ce3-89f4-30bab9add89f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDQ3NTcsIm5iZiI6MTcyMzgwNDQ1NywicGF0aCI6Ii8xNzYyODAxMjcvMzU3NTIxNTIyLTcwYjgyMTEwLTZjNjctNGNlMy04OWY0LTMwYmFiOWFkZDg5Zi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTAzNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTViOTU1MGJjMjJiNGNmODU2ODE2Njk0OWJiM2I4NWYwYzVlZjVlZTU3YTFlYjE4MDUwMzhkNTFiNjViZmE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BXJ8U-yFqMCoY5Xkf8gSL6E4eHtblN-klXS_OOGJYlk)

Hello
I have the same problem, so I created the folder myself that he can’t create and then he downloads the music but can’t move it to the final folder;
![68B22B9E-85AA-4DE0-827F-742D2D9BA050](https://github.com/user-attachments/assets/9668c89f-b9ac-4754-8971-c0e350b83674)

@KRTirtho a solution ?

**Comment by brrock** [comment]
Still happens 4.0.2

**Comment by hugomasson55** [comment]
yes

**Comment by Jayjetlee** [comment]
So no one has figured out this yet that's disappointing 😞

**Comment by hugomasson55** [comment]
@Jayjetlee yes but he is working on the problem
