### ISSUE TITLE
App doesn't load the content

### ISSUE THREAD

**Issue by 77asadian** [KRTirtho/spotube#1357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hay. Spotube won't work on my system. I'm currently using Windows 11 version 23H2 and the latest version of the Spotube. App stucks on loading the contents and nothing loads. There's just a spinning circle in the bottom left. I tested the app with and without a VPN but the issue exists. What should I do?

### Expected Behavior

I want the contents to be loaded. 

### Steps to reproduce

1. I opened the app and it didn't work.

### Operating System

Windows 11

### Spotube version

23H2

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by rubikJ** [comment]
I have the same problem
Windows 11 also

**Comment by Stauber382** [comment]
I have the same issue on Linux Tumbleweed. After installation it works one time, after restarting issue as published above. Would be great to have a solution for this :-) Love your software.

**Comment by Peperehobbit01** [comment]
You put the version of Windows 11 not the version of Spotube in Spotube version because there is no 23H2 version, it's 3.5.0 or 3.4.1 for exemple, look in the settings in the about section.

**Comment by Peperehobbit01** [comment]
@Stauber382 did you made a update of the linux core between the two launch?

**Comment by Stauber382** [comment]
Hi,
no, I didn´t make any update inbeetween. When I deinstall it and run it the first time the content loads on every page. After closing the app or a system restart the content does not load (see attached file). And it is not possible to click on play. I can only start the last song which was played when closed.
Do you need some further infos?
Thanks for your efforts! 
![Screenshot_20240403_104217](https://github.com/KRTirtho/spotube/assets/103141952/692751fa-cced-472f-8ad1-4cdf1e76b04c)

**Comment by Peperehobbit01** [comment]
That's realy weird, to help finding what is causing this issues could you send the latest log you have of the app please.

**Comment by Stauber382** [comment]
Hey,

I can send you following logs (4 different kind of errors logged): I don't use gnome, actually I use
KDE Plasma 6.0.3. I can just see that one directory/file seems to be missing and was not created in
my user folder. Maybe I could try to install it out of package and not from flatpak.

Greetings,

Stefan


============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 45 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 45
prettyName: GNOME 45 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: ffbffd065fcd44948e26eb7ac8ea30d4
------- APP INFO -------
environment: release
version: 3.5.0
appName: spotube
buildNumber: 29
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot open file, path =
'/home/stefan/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: Datei oder
Verzeichnis nicht gefunden, errno = 2)
------- STACK TRACE -------
#0 _checkForErrorResponse (dart:io/common.dart:55)
#1 _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2 _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#3 GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#4 GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#5 DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#6 GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#7 GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#8 getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#9 _RawDecoratedTitlebarButtonState.initState.<anonymous closure>
(package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>
------- CUSTOM INFO -------




============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 45 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 45
prettyName: GNOME 45 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: ffbffd065fcd44948e26eb7ac8ea30d4
------- APP INFO -------
environment: release
version: 3.5.0
appName: spotube
buildNumber: 29
packageName: spotube
---------- ERROR ----------
Error Code: 403
Forbidden.
------- STACK TRACE -------
#0 SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1 SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2 SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3 Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#4 SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:171)
<asynchronous suspension>
------- CUSTOM INFO -------





============================
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 45 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 45
prettyName: GNOME 45 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: ffbffd065fcd44948e26eb7ac8ea30d4
------- APP INFO -------
environment: release
version: 3.5.0
appName: spotube
buildNumber: 29
packageName: spotube
---------- ERROR ----------
FormatException: Unexpected character (at character 1)
Too many requests
^
------- STACK TRACE -------
#0 _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1376)
#1 _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1243)
#2 _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:908)
#3 _parseJson (dart:convert-patch/convert_patch.dart:35)
#4 JsonDecoder.convert (dart:convert/json.dart:610)
#5 JsonCodec.decode (dart:convert/json.dart:216)
#6 SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7 SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8 SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9 Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#10 SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:171)
<asynchronous suspension>
------- CUSTOM INFO -------




============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: GNOME
version: 45 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 45
prettyName: GNOME 45 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: ffbffd065fcd44948e26eb7ac8ea30d4
------- APP INFO -------
environment: release
version: 3.5.0
appName: spotube
buildNumber: 29
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot retrieve length of file, path = 'imageUrl' (OS Error: Datei oder
Verzeichnis nicht gefunden, errno = 2)
------- STACK TRACE -------
#0 _checkForErrorResponse (dart:io/common.dart:55)
#1 _File.length.<anonymous closure> (dart:io/file_impl.dart:389)
<asynchronous suspension>
#2 FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1484)
<asynchronous suspension>
#3 MultiFrameImageStreamCompleter._handleCodecReady
(package:flutter/src/painting/image_stream.dart:985)
<asynchronous suspension>
------- CUSTOM INFO -------






Am Mittwoch, dem 03.04.2024 um 01:51 -0700 schrieb Peperehobbit01:
> That's realy weird, to help finding what is causing this issues could you send the latest log you
> have of the app please.
> —
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>


[1] view it on GitHub https://github.com/KRTirtho/spotube/issues/1357#issuecomment-2033951812
[2] unsubscribe

**Comment by Peperehobbit01** [comment]
If you use KDE plasma they yes try the packages version for the distro you are using.

**Comment by 77asadian** [comment]
> You put the version of Windows 11 not the version of Spotube in Spotube version because there is no 23H2 version, it's 3.5.0 or 3.4.1 for exemple, look in the settings in the about section.

I installed the latest version of spotube 3.5.0

**Comment by 77asadian** [comment]
![Screenshot 2024-04-03 125125](https://github.com/KRTirtho/spotube/assets/116443211/a4b5fdbe-b08e-48a0-b614-b5a91dedebaa)
Here is a photo of the app when I open it.

**Comment by Stauber382** [comment]
> If you use KDE plasma they yes try the packages version for the distro you are using.

Sadly I am unable to install because the dependency jsoncpp is not fullfilled. I cannot find it anywhere to install it and the library (libjsoncpp25) was not sufficient to fullfill this dependency. Can you tell me what package is needed for that?
Thanks in advance. Anyway, the screen on windows looks the same like mine.

**Comment by Stauber382** [comment]
BTW: I installed it on my Debian-based system and I am encountering the same issues, no matter if I install it from flatpak or by .deb package :-(

**Comment by Peperehobbit01** [comment]
> ![Screenshot 2024-04-03 125125](https://private-user-images.githubusercontent.com/116443211/319123518-a4b5fdbe-b08e-48a0-b614-b5a91dedebaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzk1NDgsIm5iZiI6MTcxMjEzOTI0OCwicGF0aCI6Ii8xMTY0NDMyMTEvMzE5MTIzNTE4LWE0YjVmZGJlLWIwOGUtNDhhMC1iNjE0LWI1YTkxZGVkZWJhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMDE0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGZjMWNmODc5YjE1ZTk5NjE2MjcwZDMzYjIwOGM3OWY2NTRiYjE2MDBjOTQ1MDNkY2Q1MTM1MTJjOTczZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IQOV9hJmeoJ9PlvFn6IGCg4dOa6ZiqdQuEijrHmEnaw) Here is an image of the app when I open it.

Did you got a error message that popup?

**Comment by Peperehobbit01** [comment]
> > If you use KDE plasma they yes try the packages version for the distro you are using.
> 
> Sadly I am unable to install because the dependency jsoncpp is not fullfilled. I cannot find it anywhere to install it and the library (libjsoncpp25) was not sufficient to fullfill this dependency. Can you tell me what package is needed for that? Thanks in advance. Anyway, the screen on windows looks the same like mine.

I tried installing the .deb version myself a couple of weeks ago and found the same issues, but because the flatpak version was working I had not changed anything but now, next day, when I will be at my home whit my computer that is on Linux Mint, and not the laptop that I am using right now because it's on Windows xD. I will look to find a solution to this, and open a issues in the repos, so other devs can maybe work on fixing the issues themselves I guess and also it that way I am not gonna put my discovery for that other problem in this issues to avoid a giant mess xD.

**Comment by Stauber382** [comment]
Sounds great. Thanks for your effort- Hope it will fix the problems because I like your work!

**Comment by Peperehobbit01** [comment]
OK so i opened a issues the other day for the problem, and well the reason is that version older than 22.04 of Ubuntu and the one based of Ubuntu that are using lower version than 22.04 of Ubuntu as based are not supported. Here is the issues by the way #1373 . So look on the internet for your distro if you are using Ubuntu 22.04 or higher if yes well create a issues because it's a bug, if not, well it's normal and for the before problem, I have not advance on that yet but we still no that it hapends on flatpak and Windows tho, but it may not be for the same reason. So next step is to look into that, but it's gonna take me more time tho.

**Comment by topas-rec** [comment]
I see this on a Steam deck on Steam OS.
First time loading after install works - after reboot of the machine the playlists don't load anymore.

I didn't sign in to Spotify and use the Spotube guest mode.

Deleting the app data (cache directory of flatpak) and restarting the app (this includes walking through the apps setup again) makes the issue disappear.
Reappears on next reboot.
