### ISSUE TITLE
Flatpak Issue

### ISSUE THREAD

**Issue by rjsmith899** [KRTirtho/spotube#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Flatpak file is not functioning correctly. When I open it, all I see is a white screen. The .deb file works excellently in Linux Mint.

### Expected Behavior

The Flatpak file is not functioning correctly. When I open it, all I see is a white screen. The .deb file works excellently in Linux Mint.

### Steps to reproduce

The Flatpak file is not functioning correctly. When I open it, all I see is a white screen. The .deb file works excellently in Linux Mint. 

### Operating System

Linux Mint

### Spotube version

FlatPak Version 3.7.1

### Installation source

Flathub (Flatpak)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Peperehobbits01** [comment]
If the .deb files works fine, why are you using the flatpak anyway ? And you expected that to hapened and they are the steps to reproduced it? Like could you edit and fixed your issues please, how did you want the bug to be fixed, whit that... oh and could you provide your version of Linux Mint please?

**Comment by chrostino** [comment]
having the same issue on flatpak here. To describe it a bit more accurately, the app seems to work/interact and respond fine (except for playing music), but the whole app is completely  covered in this white layer that makes it very hard (but not impossible) to see; screenshot below

<img width="1343" height="877" alt="Image" src="https://github.com/user-attachments/assets/2b2c8e23-d1c3-4ae2-8356-0da07f14060a" />


my system is:
- Fedora 43
- Gnome 49
- Nvidia driver 580.142
- Spotube v5.1.1

`flatpak run com.github.KRTirtho.Spotube` yields:
```
Gdk-Message: 01:30:25.551: Unable to load  from the cursor theme
package:media_kit_libs_linux registered.
hetu: 1ms	to load module	hetu (compiled at 2022-08-09 10:27:17 UTC with hetu@0.4.2)
hetu: 1ms	to load module	std (compiled at 2025-11-14 06:34:06 UTC with hetu@0.4.2)
hetu: 0ms	to load module	hetu (compiled at 2022-08-09 10:27:17 UTC with hetu@0.4.2)
hetu: 0ms	to load module	otp_util (compiled at 2025-05-23 13:02:13 UTC with hetu@0.4.2)
hetu: 1ms	to load module	std (compiled at 2025-11-14 06:34:06 UTC with hetu@0.4.2)
hetu: 0ms	to load module	spotube_plugin (compiled at 2025-10-19 06:02:03 UTC with hetu@0.4.2)
hetu: 0ms	to load module	plugin (compiled at 2025-11-14 09:46:59 UTC with hetu@0.4.2)
hetu: 0ms	to parse	[$script_6b137ed7: import "module:plu...]
hetu: 0ms	to bundle	[$script_6b137ed7: import "module:plu...]
hetu: 0ms	to compile	[$script_6b137ed7: import "module:plu...]
hetu: 1ms	to load module	$script_6b137ed7: import "module:plu... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)
hetu: 0ms	to load module	otp_util (compiled at 2025-05-23 13:02:13 UTC with hetu@0.4.2)
hetu: 1ms	to load module	spotube_plugin (compiled at 2025-10-19 06:02:03 UTC with hetu@0.4.2)
hetu: 7ms	to load module	plugin (compiled at 2026-02-20 16:28:00 UTC with hetu@0.4.2)
hetu: 0ms	to parse	[$script_55d257e5: import "module:plu...]
hetu: 0ms	to bundle	[$script_55d257e5: import "module:plu...]
hetu: 0ms	to compile	[$script_55d257e5: import "module:plu...]
hetu: 1ms	to load module	$script_55d257e5: import "module:plu... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)
hetu: 0ms	to parse	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to bundle	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to compile	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to load module	$script_7eabcfc4: metadataPlugin.aut... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)
hetu: 0ms	to parse	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to bundle	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to compile	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to load module	$script_7366b485: metadataPlugin.aut... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)
hetu: 0ms	to parse	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to bundle	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to compile	[$script_7eabcfc4: metadataPlugin.aut...]
hetu: 0ms	to load module	$script_7eabcfc4: metadataPlugin.aut... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)
hetu: 1ms	to parse	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to bundle	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to compile	[$script_7366b485: metadataPlugin.aut...]
hetu: 0ms	to load module	$script_7366b485: metadataPlugin.aut... (compiled at 2026-04-06 23:30:26 UTC with hetu@0.4.2)

```

log from the Logs section in spotube settings
```
[2026-04-07 01:30:25.974384]---------------------
org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:625)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:85)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:73)
<asynchronous suspension>

----------------------------------------
:82)
#9      _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#10     HookElement._use (package:flutter_hooks/src/framework.dart:486)
#11     Hook.use (package:flutter_hooks/src/framework.dart:139)
#12     use (package:flutter_hooks/src/framework.dart:18)
#13     useMemoized (package:flutter_hooks/src/primitives.dart:61)
#14     BottomPlayer.build (package:spotube/modules/root/bottom_player.dart:37)
#15     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
#16     StatefulElement.build (package:flutter/src/widgets/framework.dart:5833)
#17     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
#18     HookElement.build (package:flutter_hooks/src/framework.dart:438)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5723)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5884)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5435)
#22     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2695)
#23     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1259)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1434)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1347)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200)
#30     _rootRun (dart:async/zone.dart:1525)
#31     _CustomZone.run (dart:async/zone.dart:1422)
#32     _CustomZone.runGuarded (dart:async/zone.dart:1321)
#33     _invoke (dart:ui/hooks.dart:332)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444)
#35     _drawFrame (dart:ui/hooks.dart:302)

----------------------------------------
[2026-04-07 01:30:25.979478]---------------------
PathNotFoundException: Cannot open file, path = '/home/brudda/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:58)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:442)
#2      _rootRunUnary (dart:async/zone.dart:1538)
#3      _CustomZone.runUnary (dart:async/zone.dart:1429)
<asynchronous suspension>
#4      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:649)
<asynchronous suspension>
#5      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#6      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#7      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#8      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#9      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#10     getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#11     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2026-04-07 01:30:26.000075]---------------------
Null check operator used on a null value
#0      SpotubeImageExtensions.asUrlString.<anonymous closure> (package:spotube/models/metadata/image.dart:36)
#1      Sort._insertionSort (dart:_internal/sort.dart:77)
#2      Sort._doSort (dart:_internal/sort.dart:62)
#3      Sort.sort (dart:_internal/sort.dart:33)
#4      ListBase.sort (dart:collection/list.dart:321)
#5      IterableExtension.sorted (package:collection/src/iterable_extensions.dart:66)
#6      SpotubeImageExtensions.asUrlString (package:spotube/models/metadata/image.dart:36)
#7      BottomPlayer.build.<anonymous closure> (package:spotube/modules/root/bottom_player.dart:39)
#8      _MemoizedHookState.value (package:flutter_hooks/src/primitives.dart:82)
#9      _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#10     HookElement._use (package:flutter_hooks/src/framework.dart:486)
#11     Hook.use (package:flutter_hooks/src/framework.dart:139)
#12     use (package:flutter_hooks/src/framework.dart:18)
#13     useMemoized (package:flutter_hooks/src/primitives.dart:61)
#14     BottomPlayer.build (package:spotube/modules/root/bottom_player.dart:37)
#15     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
#16     StatefulElement.build (package:flutter/src/widgets/framework.dart:5833)
#17     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
#18     HookElement.build (package:flutter_hooks/src/framework.dart:438)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5723)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5884)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5435)
#22     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2695)
#23     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1259)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1434)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1347)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200)
#30     _rootRun (dart:async/zone.dart:1525)
#31     _CustomZone.run (dart:async/zone.dart:1422)
#32     _CustomZone.runGuarded (dart:async/zone.dart:1321)
#33     _invoke (dart:ui/hooks.dart:332)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444)
#35     _drawFrame (dart:ui/hooks.dart:302)

----------------------------------------
[2026-04-07 01:30:26.081292]---------------------
Null check operator used on a null value
#0      SpotubeImageExtensions.asUrlString.<anonymous closure> (package:spotube/models/metadata/image.dart:36)
#1      Sort._insertionSort (dart:_internal/sort.dart:77)
#2      Sort._doSort (dart:_internal/sort.dart:62)
#3      Sort.sort (dart:_internal/sort.dart:33)
#4      ListBase.sort (dart:collection/list.dart:321)
#5      IterableExtension.sorted (package:collection/src/iterable_extensions.dart:66)
#6      SpotubeImageExtensions.asUrlString (package:spotube/models/metadata/image.dart:36)
#7      BottomPlayer.build.<anonymous closure> (package:spotube/modules/root/bottom_player.dart:39)
#8      _MemoizedHookState.value (package:flutter_hooks/src/primitives.dart:82)
#9      _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#10     HookElement._use (package:flutter_hooks/src/framework.dart:486)
#11     Hook.use (package:flutter_hooks/src/framework.dart:139)
#12     use (package:flutter_hooks/src/framework.dart:18)
#13     useMemoized (package:flutter_hooks/src/primitives.dart:61)
#14     BottomPlayer.build (package:spotube/modules/root/bottom_player.dart:37)
#15     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
#16     StatefulElement.build (package:flutter/src/widgets/framework.dart:5833)
#17     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
#18     HookElement.build (package:flutter_hooks/src/framework.dart:438)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5723)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5884)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5435)
#22     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2695)
#23     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1259)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1434)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1347)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200)
#30     _rootRun (dart:async/zone.dart:1525)
#31     _CustomZone.run (dart:async/zone.dart:1422)
#32     _CustomZone.runGuarded (dart:async/zone.dart:1321)
#33     _invoke (dart:ui/hooks.dart:332)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444)
#35     _drawFrame (dart:ui/hooks.dart:302)

----------------------------------------
[2026-04-07 01:30:26.122320]---------------------
Null check operator used on a null value
#0      SpotubeImageExtensions.asUrlString.<anonymous closure> (package:spotube/models/metadata/image.dart:36)
#1      Sort._insertionSort (dart:_internal/sort.dart:77)
#2      Sort._doSort (dart:_internal/sort.dart:62)
#3      Sort.sort (dart:_internal/sort.dart:33)
#4      ListBase.sort (dart:collection/list.dart:321)
#5      IterableExtension.sorted (package:collection/src/iterable_extensions.dart:66)
#6      SpotubeImageExtensions.asUrlString (package:spotube/models/metadata/image.dart:36)
#7      BottomPlayer.build.<anonymous closure> (package:spotube/modules/root/bottom_player.dart:39)
#8      _MemoizedHookState.value (package:flutter_hooks/src/primitives.dart:82)
#9      _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#10     HookElement._use (package:flutter_hooks/src/framework.dart:486)
#11     Hook.use (package:flutter_hooks/src/framework.dart:139)
#12     use (package:flutter_hooks/src/framework.dart:18)
#13     useMemoized (package:flutter_hooks/src/primitives.dart:61)
#14     BottomPlayer.build (package:spotube/modules/root/bottom_player.dart:37)
#15     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
#16     StatefulElement.build (package:flutter/src/widgets/framework.dart:5833)
#17     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
#18     HookElement.build (package:flutter_hooks/src/framework.dart:438)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5723)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5884)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5435)
#22     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2695)
#23     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1259)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1434)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1347)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1200)
#30     _rootRun (dart:async/zone.dart:1525)
#31     _CustomZone.run (dart:async/zone.dart:1422)
#32     _CustomZone.runGuarded (dart:async/zone.dart:1321)
#33     _invoke (dart:ui/hooks.dart:332)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444)
#35     _drawFrame (dart:ui/hooks.dart:302)

----------------------------------------
[2026-04-07 01:30:26.469097]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:523)
<asynchronous suspension>
#1      HttpClient.request (package:hetu_std/http/http.dart:146)
<asynchronous suspension>
#2      HttpClient.post (package:hetu_std/http/http.dart:189)
<asynchronous suspension>
#3      StreamBinding.hFetch.<anonymous closure>.<anonymous closure> (package:hetu_std/stream/stream.binding.dart:84)
<asynchronous suspension>
#4      StreamBinding.hFetch.<anonymous closure>.<anonymous closure> (package:hetu_std/stream/stream.binding.dart:84)
<asynchronous suspension>
#5      MetadataPluginTrackEndpoint.radio (package:spotube/services/metadata/endpoints/track.dart:31)
<asynchronous suspension>
#6      useEndlessPlayback.<anonymous closure>.listener (package:spotube/hooks/configurators/use_endless_playback.dart:27)
<asynchronous suspension>

----------------------------------------
