### ISSUE TITLE
Black screen on spotify sign in

### ISSUE THREAD

**Issue by howboutsleep** [KRTirtho/spotube#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to sign in after logging out due to issue described here: #1403 I get black screen. Pure reinstall did not fix the issue (still black screen at sign in attempt)

### Expected Behavior

Being able to log into spotify account

### Steps to reproduce

Opened the app while not logged into spotify and tried to log in

### Operating System

Android

### Spotube version

v3.8.0

### Installation source

Website (spotube.krtirtho.dev), F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by FlameGrowl-wq** [comment]
linux mint too

**Comment by arenekosreal** [comment]
Arch Linux also has this problem. Only `package:media_kit_libs_linux registered.` in terminal output, and closing program by clicking close button is not working, I can only use Ctrl+C to stop spotube running in terminal.

**Comment by arenekosreal** [comment]
More info:
![screenshot of spotube](https://github.com/user-attachments/assets/c8e708a0-793b-4956-a6a7-421a30146234)

Terminal output when running a self-built debug binary:
```
$ ./spotube
package:media_kit_libs_linux registered.
flutter: The Dart VM service is listening on http://127.0.0.1:39415/HFmxGZmHQEo=/
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ Invalid argument(s): Failed to load dynamic library 'libmetadata_god.so': /home/zhanghua/aur/spotube/src/spotube-3.8.0/build/linux/x64/debug/bundle/lib/libmetadata_god.so: undefined symbol: Dart_NewPersistentHandle_DL
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
flutter: │ #1   new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: │ #2   new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47)
flutter: │ #3   loadExternalLibraryRaw.<anonymous closure> (package:flutter_rust_bridge/src/loader/_io.dart:80:46)
flutter: │ #4   loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22)
flutter: │ #5   loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:79:12)
flutter: │ #6   loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
flutter: │ #7   BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:129:13)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ Invalid argument(s): Failed to load dynamic library 'libflutter_discord_rpc.so': /home/zhanghua/aur/spotube/src/spotube-3.8.0/build/linux/x64/debug/bundle/lib/libflutter_discord_rpc.so: undefined symbol: Dart_NewPersistentHandle_DL
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
flutter: │ #1   new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: │ #2   new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47)
flutter: │ #3   loadExternalLibraryRaw.<anonymous closure> (package:flutter_rust_bridge/src/loader/_io.dart:80:46)
flutter: │ #4   loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22)
flutter: │ #5   loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:79:12)
flutter: │ #6   loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
flutter: │ #7   BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:129:13)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

It seems that the problem is related to https://github.com/KRTirtho/frb_plugins but I have no idea about this.

**Comment by arenekosreal** [comment]
Nevermind, mine problem is that I build spotube with LTO enabled. After removing LTO flags, the problem disappeared.

**Comment by fareed-hameed** [comment]
I have  the same issue with Android 9 and Android 10

----------------------------------------
[2024-11-06 20:41:35.596980]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-06 20:41:35.818068]---------------------
Error Code: 401
Valid user authentication required
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#4      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-06 20:41:35.888025]---------------------
Error Code: 403
Insufficient client scope
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#4      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------

**Comment by Edgaras1** [comment]
I also encountered this issue on Linux. A temporary solution was to set the environment variable WEBKIT_DISABLE_COMPOSITING_MODE=1 before starting Spotube
