### ISSUE TITLE
Spotube skipping songs when switching sources

### ISSUE THREAD

**Issue by LOLYOUz12** [KRTirtho/spotube#1909]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Songs being automatically skipped when changing sources, even when relistening to the song.

### Expected Behavior

1. Changing sources for songs
2. Song plays from that source

### Steps to reproduce

1. Play a song
2. Chooses a different source
3. Song is skipped when that source plays

https://github.com/user-attachments/assets/524b4c9c-c7bf-4004-8699-e0ef4b5f5757

### Logs

[2024-09-23 01:15:21.516531]---------------------
Bad state: The provider AutoDisposeStreamProvider<String>#e0a40 was disposed during loading state, yet no value could be emitted.
#0      FutureHandlerProviderElementMixin.dispose (package:riverpod/src/async_notifier/base.dart:460)
#1      StreamProviderElement.dispose (package:riverpod/src/stream_provider/base.dart:170)
#2      ProviderContainer._disposeProvider (package:riverpod/src/framework/container.dart:319)
#3      ProviderScheduler._performDispose (package:riverpod/src/framework/scheduler.dart:128)
#4      ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:83)
#5      ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41)
#6      _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:396)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171)
#15     _rootRun (dart:async/zone.dart:1399)
#16     _CustomZone.run (dart:async/zone.dart:1301)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#18     _invoke (dart:ui/hooks.dart:314)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#20     _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------

### Operating System

Android 13

### Spotube version

v3.8.1

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by lzccr** [comment]
same thing happened to me. sometimes this happens to me when I am trying to play a song when another song is playing.

**Comment by skywalker478** [comment]
Same here. What's more the song becomes unplayable until Spotube is restarted.

**Comment by OnyxJet** [comment]
I've discovered this on android as well.

**Comment by Peperehobbits01** [comment]
It's on the .deb on Mint 22 to. I think, it's for all devices.
