### ISSUE TITLE
Does not play music and transition time.

### ISSUE THREAD

**Issue by fbiof** [KRTirtho/spotube#1941]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

The app does not play any music. It keeps skipping from one song to another and doesn’t play any. When it works, it takes a long time to play a chosen track and transition from one song to another.

### Expected Behavior

That it plays music and reduces the transition time from one song to another.

### Steps to reproduce

I opened the app. I searched the playlist for the song I wanted to play. I clicked on it. At the bottom, the name of the song and the 'play' icon appeared as loading, but the music didn’t play. Then it kept skipping the names of the songs and didn’t play any.

### Logs

----------------------------------------
[2024-09-29 10:24:32.515387]---------------------
Failed to open http://0.0.0.0:6362/stream/0yp3TvJNlG50Q4tAHWNCRm.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------

### Operating System

Android 

### Spotube version

v3.8.1

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by RomanKnight11** [comment]
Im having a similar issue, i want to play music via spotube, but when i click play it just shows as loading, then it just doesnt play whatsoever, ive tried uninstalling it and reinstalling it many many times but still get the same issue, i have also tried sigining in to multiple different spotify accounts aswell

**Comment by mp3skater** [comment]
I have this issue too, it first occurred when i upgraded to the newest version, the old one was working. I'm using a redmi 9 pro with android, no restrictions or sim stuff..

**Comment by IAowSwels** [comment]
Did you really search for this issue? Because it is already pretty known. V.3.8.4 nightly worked for me using W10. Didn't try on Android.

**Comment by abyss-mal** [comment]
i found a solution, it's likely because of the recent contract issue w/ youtube !! if you change where the playback comes from, spotube works again. go to settings and it's one of the 1st few things you can change.

**Comment by fbiof** [comment]
> Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 nightly trabalhado para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4

I use the app for Android, directly from Google Play. I installed this version you sent. The music starts playing and the app closes by itself.

**Comment by fbiof** [comment]
> Encontrei uma solução, provavelmente por causa do recente problema de contrato com o YouTube!! Se você alterar a origem da reprodução, o Spotify funcionará novamente. Vá para as configurações e essa é uma das primeiras coisas que você pode alterar.


I changed the audio source as suggested, but it didn't help.

**Comment by Finalshare90** [comment]
> > Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 nightly trabalhado para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4
> 
> I use the app for Android, directly from Google Play. I installed this version you sent. The music starts playing and the app closes by itself.

Working fine in linux aswell, couldn't get other sources running, but still works fine in Youtube + WebA codec, changing the codec may fix some peoples issues.

**Comment by SpyrosD** [comment]
> > Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 nightly trabalhado para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4
> 
> I use the app for Android, directly from Google Play. I installed this version you sent. The music starts playing and the app closes by itself.

Regarding 3.8.4 .apk for Android: disable the notifications under app settings; this worked for me (lenovo tablet w/ android 11)

**Comment by TipsyTheCat** [comment]
> > > Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 nightly trabalhado para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4
> > 
> > 
> > I use the app for Android, directly from Google Play. I installed this version you sent. The music starts playing and the app closes by itself.
> 
> Regarding 3.8.4 .apk for Android: disable the notifications under app settings; this worked for me (lenovo tablet w/ android 11)

neither the release or nightly even use the notification APIs on Android.
![Screenshot_20240930-125648](https://github.com/user-attachments/assets/c1084b5e-6e25-4c3f-8c08-e0c2f30be43b)
![Screenshot_20240930-125724](https://github.com/user-attachments/assets/45306945-d84a-4351-8754-2c8be830d849)

**Comment by TipsyTheCat** [comment]
UPDATE: a new update just came through on the app store that fixes this!

**Comment by SpyrosD** [comment]
> > > > Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 nightly trabalhado para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4
> > > 
> > > 
> > > I use the app for Android, directly from Google Play. I installed this version you sent. The music starts playing and the app closes by itself.
> > 
> > 
> > Regarding 3.8.4 .apk for Android: disable the notifications under app settings; this worked for me (lenovo tablet w/ android 11)
> 
> neither the release or nightly even use the notification APIs on Android. (Pixel 8a running stock android 14) ![Screenshot_20240930-125648](https://private-user-images.githubusercontent.com/97964375/372175112-c1084b5e-6e25-4c3f-8c08-e0c2f30be43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTc5NjAsIm5iZiI6MTcyNzcxNzY2MCwicGF0aCI6Ii85Nzk2NDM3NS8zNzIxNzUxMTItYzEwODRiNWUtNmUyNS00YzNmLThjMDgtZTBjMmYzMGJlNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE3MzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjg5ZmYyYjNiZDhjYzcyMjI5ZDA2OGMwZTRlMDRhMzkzMWJlYjQwMzdjMzMwZjg4YjY4YTUyNjA4OGI1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LzcsGx5GA_0zEky0QDlZ9ha-QG9pjAFzRgyjwtM5jQU) ![Screenshot_20240930-125724](https://private-user-images.githubusercontent.com/97964375/372175291-45306945-d84a-4351-8754-2c8be830d849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTc5NjAsIm5iZiI6MTcyNzcxNzY2MCwicGF0aCI6Ii85Nzk2NDM3NS8zNzIxNzUyOTEtNDUzMDY5NDUtZDg0YS00MzUxLTg3NTQtMmM4YmU4MzBkODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE3MzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODI3NTQzMWM0ZDQyYTllMmYwYzBkNGQ4OTJjYjM1M2E1MDc2M2Q1NmJlNDI2MmMyNzJiMzE1NGQ3MTEyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KS6gtvtZkXexjxuxsZqcjSNqRtfkVKz-lGxH5eCNkV8)

I installed the 3.8.4 nightly in my tablet (lenovo tb-x306f - android 11 stock); the app was not functional.
I went to the tablet settings => applications => spotube => notifications and I disabled them. I missed the spotube menu in the notifications area (the drop-down menu at the top) but the app is working properly now.
***UPDATE*** Just tested on the same tablet the 3.8.2 stable build 35 and it is working properly!!
THANK YOU ALL!!! the best music app is up+running again!!!

**Comment by brockhaus** [comment]
My linux version does work now again! Thank you!
Will the Android version be on FDroid soon, too? :)
Anyways: Thanks!

**Comment by fbiof** [comment]
> > > Você realmente percebeu esse problema? Porque ele já é bem conhecido. V.3.8.4 trabalho noturno para mim usando W10. Não tentei no Android, mas não deve funcionar ainda. https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4
> > 
> > 
> > Eu uso o aplicativo para Android, direto do Google Play. Eu instalei essa versão que você enviou. A música começa a tocar e o aplicativo fecha sozinho.
> 
> Em relação ao 3.8.4 .apk para Android: desabilite as notificações nas configurações do aplicativo; isso funcionou para mim (tablet Lenovo com Android 11)

In relation to version 3.8.4.apk, I searched within the app for the notification option and couldn't find it. I went to the app notifications in the Android system, and the notifications for the app are blocked, and the notifications option was already disabled, but it still doesn't work.

**Comment by fbiof** [comment]
> ATUALIZAÇÃO: uma nova atualização acabou de chegar na app store que corrige isso!

It started working again with the change. The transition between songs still takes a little while. The longer ones take about 10 seconds, but that's okay. The important thing is that it works again; that's what matters.

**Comment by fbiof** [comment]
It started working again with the change. The transition between songs still takes a little while. The longer ones take about 10 seconds, but that's okay. The important thing is that it works again; that's what matters.

**Comment by KRTirtho** [comment]
Duplicate of #1916
