### ISSUE TITLE
Search does not searching music with "#" included in the name

### ISSUE THREAD

**Issue by TheGetHuber** [KRTirtho/spotube#1977]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

While seraching music with symbol "#" Spotube returns "Error Code: 400 \n Missing parameter type".
Example of the error:
![image](https://github.com/user-attachments/assets/29ad7bfa-d4ee-42ab-a2e2-f8c0f312e2fb)

### Expected Behavior

Music be able searched with "#" character included in the name
Same music but with "#" removed:
![image](https://github.com/user-attachments/assets/86895e7a-dfd7-49c2-81a8-ce2e601a6b41)

### Steps to reproduce

1. Open app
2. Open the search
3. Type "#" or any other string with "#" included
4. Look how error appears under the serachbar

### Logs

<details>
<summary>Logs</summary>

```
[2024-10-08 20:02:57.415047]---------------------
Error Code: 400
No search query
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      BundledPages._parseBundledPage (package:spotify/src/endpoints/endpoint_paging.dart:324)
<asynchronous suspension>
#4      SearchNotifier.fetch (package:spotube/provider/spotify/search/search.dart:47)
<asynchronous suspension>
#5      SearchNotifier.build (package:spotube/provider/spotify/search/search.dart:74)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 20:02:57.503988]---------------------
Error Code: 400
No search query
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      BundledPages._parseBundledPage (package:spotify/src/endpoints/endpoint_paging.dart:324)
<asynchronous suspension>
#4      SearchNotifier.fetch (package:spotube/provider/spotify/search/search.dart:47)
<asynchronous suspension>
#5      SearchNotifier.build (package:spotube/provider/spotify/search/search.dart:74)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 20:02:57.506521]---------------------
Error Code: 400
No search query
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      BundledPages._parseBundledPage (package:spotify/src/endpoints/endpoint_paging.dart:324)
<asynchronous suspension>
#4      SearchNotifier.fetch (package:spotube/provider/spotify/search/search.dart:47)
<asynchronous suspension>
#5      SearchNotifier.build (package:spotube/provider/spotify/search/search.dart:74)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------

```
</details>

### Operating System

Linux

### Spotube version

v3.8.2 stable

### Installation source

GitHub Releases (Binary)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by D1mar0n** [comment]
Search doesn't work. Tested on version 3.8.2 / 3.8.3. 
![2024-10-10_080349](https://github.com/user-attachments/assets/40af4b66-a0c8-463b-b648-a335491bf9a1)
Windows 11 24H2 (x64)

**Comment by KRTirtho** [comment]
@D1mar0n change your marketplace from "Settings" > "Marketplace" to one supported by Spotify

**Comment by D1mar0n** [comment]
Hello! Thank you very much for your answer. Your hint worked - if you select any country except Russia as your location, the search works.
На Чт.10.10.2024 17:48:00, Kingkor Roy Tirtho ***@***.***> написал(а):
@D1mar0n [https://github.com/D1mar0n] change your marketplace from "Settings" > "Marketplace" to one supported by Spotify

**Comment by KRTirtho** [comment]
Of course. Lots of US & EU services has stopped providing service for Russia. Spotify is one of them

**Comment by D1mar0n** [comment]
Thanks for the hint, I already figured it out...
На Вс.13.10.2024 19:48:03, Kingkor Roy Tirtho ***@***.***> написал(а):
Of course. Lots of US & EU services has stopped providing service for Russia. Spotify is one of them
