### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by skruglov2023** [KRTirtho/spotube#1979]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

App doesn't play anything with youtube as source

### Expected Behavior

Both devices should be playing music

### Steps to reproduce

open app
choose a song
Song doesn't play, just keeps skipping over songs. 
Can't set piped as source as it doesn't have the right song. 

### Logs

[2024-10-08 23:01:11.760585]---------------------
YoutubeExplodeException: Video cRkaPdfjzEk returned 403 (stream: 137
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:11.767503]---------------------
Failed to open http://0.0.0.0:20620/stream/0RAn8LOs5QVMLy2xH30bUj.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-10-08 23:01:22.398272]---------------------
YoutubeExplodeException: Video PAyOcwZggnA returned 403 (stream: 18
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:26.650759]---------------------
YoutubeExplodeException: Video t4QK8RxCAwo returned 403 (stream: 137
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      SiblingTracksSheet.build.<anonymous closure>.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:114)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#6      SiblingTracksSheet.build.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:109)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:27.949240]---------------------
YoutubeExplodeException: Video t4QK8RxCAwo returned 403 (stream: 137
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      SiblingTracksSheet.build.<anonymous closure>.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:114)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#6      SiblingTracksSheet.build.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:109)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:44.152422]---------------------
[MediaKitError] 
Failed to open http://0.0.0.0:11186/stream/1QEEqeFIZktqIpPI4jSVSF.
#0      new CustomPlayer.<anonymous closure> (package:spotube/services/audio_player/custom_player.dart:51)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-10-08 23:01:48.232320]---------------------
YoutubeExplodeException: Video 3dOx510kyOs returned 403 (stream: 135
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:49.576333]---------------------
YoutubeExplodeException: Video PAyOcwZggnA returned 403 (stream: 18
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:49.578265]---------------------
[MediaKitError] 
Failed to open http://0.0.0.0:11186/stream/0bRNszTbTFLNlunAeh7eom.
#0      new CustomPlayer.<anonymous closure> (package:spotube/services/audio_player/custom_player.dart:51)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-10-08 23:01:49.942918]---------------------
VideoUnplayableException: Video '7wRHBLwpASw' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are 
some restrictions in place that prevent watching this video.
Reason: Please sign in
#0      StreamClient._getCipherStream (package:youtube_explode_dart/src/videos/streams/stream_client.dart:179)
<asynchronous suspension>
#1      StreamClient._getStreams (package:youtube_explode_dart/src/videos/streams/stream_client.dart:137)
<asynchronous suspension>
#2      Stream.toList.<anonymous closure> (dart:async/stream.dart:1351)
<asynchronous suspension>
#3      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:37)
<asynchronous suspension>
#4      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#6      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#7      SiblingTracksSheet.build.<anonymous closure>.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:114)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#9      SiblingTracksSheet.build.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:109)
<asynchronous suspension>

----------------------------------------
[2024-10-08 23:01:50.505436]---------------------
YoutubeExplodeException: Video 7wRHBLwpASw returned 403 (stream: 137
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      SiblingTracksSheet.build.<anonymous closure>.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:114)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#6      SiblingTracksSheet.build.<anonymous closure> (package:spotube/modules/player/sibling_tracks_sheet.dart:109)
<asynchronous suspension>

----------------------------------------

### Operating System

Windows 11 23H2, Android 14

### Spotube version

3.8.2

### Installation source

Website (spotube.krtirtho.dev), Play Store (Android)

### Additional information

So far I've tried reinstalling the app on both devices, signing in/out of spotify, changing to a different playlist or specific song. Nothing plays. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by SissioMisio** [comment]
Same here

**Comment by hervoan** [comment]
same here, runing on android and windows.

**Comment by Sweet-Paw** [comment]
Same here, Windows

**Comment by s-b-repo** [comment]
please can we use **invidious.io** as a source

**Comment by XaviFortes** [comment]
Same issue here, running windows.

**Comment by ThierryParis** [comment]
same for me.
Perhaps youtube has found how to detect spotube and limit our access ?

**Comment by skruglov2023** [comment]
> same for me. Perhaps youtube has found how to detect spotube and limit our access ?

If that's the case, that's 2 open source apps I've lost in under a month (the other being snapenhance)

If I had the time and more in-depth knowledge I'd help out with code to adjust to whatever "defense" the big corporations are trying to play, but unfortunately I'm in college and have very minimal app dev knowledge.

**Comment by DLAcoding** [comment]
Same here since today (on Windows)

**Comment by AhmedAlaaGenina** [comment]
**### before updating to 2.2.3 it happen in IOS** 
**after update i get muxed with empty data**
```
      final video = await _yt.videos.get(youtubeUrl);
      final manifest = await _yt.videos.streamsClient.getManifest(video.id);
      final muxedStreams = manifest.muxed;
      final muxedUrls = muxedStreams.toList().toSet();
      log("muxedStreams: ${manifest.muxed}");
```
**### the log => [log] muxedStreams: []**

**Comment by XaviFortes** [comment]
> **### before updating to 2.2.3 it happen in IOS** **after update i get muxed with empty data**
> 
> ```
>       final video = await _yt.videos.get(youtubeUrl);
>       final manifest = await _yt.videos.streamsClient.getManifest(video.id);
>       final muxedStreams = manifest.muxed;
>       final muxedUrls = muxedStreams.toList().toSet();
>       log("muxedStreams: ${manifest.muxed}");
> ```
> 
> **### the log => [log] muxedStreams: []**

Spotube is not on iOS

**Comment by ThierryParis** [comment]
@XaviFortes , you should look at the download page :-)
https://spotube.krtirtho.dev/downloads

**Comment by XaviFortes** [comment]
@ThierryParis My bad didn't know it was there as it doesn't appears on the readme and on the tags of the repo haha

**Comment by skruglov2023** [comment]
Latest update 3.8.3 fixes problem.

**Comment by ThierryParis** [comment]
Thanks
