### ISSUE TITLE
again bug download music on custom android folder

### ISSUE THREAD

**Issue by xunil89** [KRTirtho/spotube#2001]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

downloading tracks goes wrong when the destination folder is on external memory sd

### Expected Behavior

download start 

### Logs

[2024-10-15 07:33:32.132481]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 416 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 416 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      DioForNative.download (package:dio/src/dio/dio_for_native.dart:46)
<asynchronous suspension>
#2      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:104)
<asynchronous suspension>
#3      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:402)
<asynchronous suspension>

----------------------------------------
[2024-10-15 07:33:35.991734]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 416 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 416 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      DioForNative.download (package:dio/src/dio/dio_for_native.dart:46)
<asynchronous suspension>
#2      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:104)
<asynchronous suspension>
#3      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:402)
<asynchronous suspension>

----------------------------------------

### Operating System

Android

### Spotube version

3.8.3 (36)

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by xunil89** [comment]
version 4.0 continues to not work download on custom folder
[2025-03-11 13:11:42.852202]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 416 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 416 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      DioForNative.download (package:dio/src/dio/dio_for_native.dart:46)
<asynchronous suspension>
#2      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:104)
<asynchronous suspension>
#3      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:402)
<asynchronous suspension>

----------------------------------------
