### ISSUE TITLE
Cannot play videos that have the "Viewer discretion is advised" youtube warning

### ISSUE THREAD

**Issue by Bowarc** [KRTirtho/spotube#2008]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

In the current version (3.8.3), trying to play a song where the yt video has a "Viewer discretion is advised" warning (like [Jake Hill & Josh A - Suicidal Thoughts](https://www.youtube.com/watch?v=VFSg01HDqAk)) does not work.

### Expected Behavior

To be able to play that song.

Maybe using yt login ? idk, that's what the log suggests

### Steps to reproduce

1. Open the app
2. Search `suicidal thoughts jake hill`
3. Play the first one

### Logs

<details>
<summary>Logs</summary>

```
----------------------------------------
[2024-10-17 12:03:33.819436]---------------------
VideoUnplayableException: Video 'VFSg01HDqAk' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are 
some restrictions in place that prevent watching this video.
Reason: Please sign in
#0      StreamClient._getCipherStream (package:youtube_explode_dart/src/videos/streams/stream_client.dart:179)
<asynchronous suspension>
#1      StreamClient._getStreams (package:youtube_explode_dart/src/videos/streams/stream_client.dart:137)
<asynchronous suspension>
#2      Stream.toList.<anonymous closure> (dart:async/stream.dart:1351)
<asynchronous suspension>
#3      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:37)
<asynchronous suspension>
#4      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:963)
<asynchronous suspension>
#6      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#7      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#8      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#9      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#10     sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#11     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

```
</details>

### Operating System

W 10

### Spotube version

3.8.3

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
This is an underlying bug in the `youtube_explode_dart` library. But invidious or piped can get streams for these kind of videos. So this should be something fixable

**Comment by Bowarc** [comment]
I tried some piped instances but none worked atm

**Comment by KRTirtho** [comment]
Upstream issue https://github.com/Hexer10/youtube_explode_dart/issues/299
