### ISSUE TITLE
issue authenticating with last fm

### ISSUE THREAD

**Issue by christophernewton** [KRTirtho/spotube#2025]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20241025-115718](https://github.com/user-attachments/assets/c7907c2a-b635-4eaa-8fdb-f289653d2ce6)
When logging in with account on last fm or shows the following error

I can login to the site a normal with no issue, just authenticating in app is an issue.

Ref: https://lastfm-docs.github.io/api-docs/codes/#lastfm-error-code-4-authentication-failed

### Expected Behavior

Be able to login to last fm with my own credentials

### Steps to reproduce

1. Open app
2. I logged in with Spotify
3. Log in with last fm
4. Screenshot is attached above

### Logs

<details>
<summary>Logs</summary>

```
y_box.dart:111)
#784    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#785    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#786    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#787    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#788    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#789    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#790    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#791    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#792    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#793    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#794    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#795    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#796    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#797    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#798    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#799    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3726)
#800    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#801    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#802    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#803    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1002)
#804    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1311)
#805    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446)
#806    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052)
#807    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065)
#808    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602)
#809    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164)
#810    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#811    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#812    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#813    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#814    _rootRun (dart:async/zone.dart:1399)
#815    _CustomZone.run (dart:async/zone.dart:1301)
#816    _CustomZone.runGuarded (dart:async/zone.dart:1209)
#817    _invoke (dart:ui/hooks.dart:314)
#818    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#819    _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------
[2024-10-25 11:36:01.831254]---------------------
Error Code: 403
Insufficient client scope
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#4      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------

```
</details>

### Operating System

android

### Spotube version

3.8.3

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by s-b-repo** [comment]
Last.fm Error Code 4: Authentication Failed¶ This error emits when a request is made signed with a session token that has been generated for an account that has revoked access to your application.

**Comment by s-b-repo** [comment]
#2025) for Spotube involves an authentication failure with Last.fm when logging in through the app, though logging in directly on the Last.fm website works fine. The error log indicates a 403 - Insufficient client scope, suggesting a possible mismatch in API permissions. This might be due to an expired or revoked session token or incorrect handling of scopes. Possible solutions include re-verifying API key and secret settings, adjusting scopes, and ensuring proper token management. Further investigation into OAuth settings for both Last.fm and Spotify might resolve the issue.

**Comment by herdivineshadow** [comment]
I get this error when attempting to logging in to last.fm through the app:

![image_2024-11-25_201726865](https://github.com/user-attachments/assets/c77f1746-9f55-4305-8470-59e69202b450)

Although after this fail message, Spotube does show up on the Connected Applications page:

![image_2024-11-25_201849286](https://github.com/user-attachments/assets/f412235f-d555-4280-a91c-9f645fb45e1d)

However when I play music in Spotube, nothing scrobbles.s

**Comment by DMJoh** [comment]
I tried to login with email account and encountered this error. However, when I tried to login with username, it worked.

**Comment by s-b-repo** [comment]
we can try to make a tool that converts email to user name we can use sherlock tool for inspiration

**Comment by onokatio** [comment]
I have same problem and this solved the issue ! Thank you.

> we can try to make a tool that converts email to user name we can use sherlock tool for inspiration

**Comment by arghanath007** [comment]
Instead of Email and password, use your username with password and it will work, at least for me it did. Try that out.

**Comment by christophernewton** [comment]
That seems to have solved it ty!
