### ISSUE TITLE
Spotube causes Android UI to bug out/hang/lag/freeze up real bad when playing songs

### ISSUE THREAD

**Issue by Kaidep13** [KRTirtho/spotube#2082]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Spotube causes Android UI to bug out/hang/freeze up real bad when playing songs. It only happens when i click the play button. If the app isn't actively playing music, everything is smooth and works fine.

If i stay in the app as well when playing tracks, everything works fine. The moment i get out of the app(the drawer, quick settings or even on the lock screen), the android UI lags so much that the device becomes unusable. If i somehow manages to pause playing from the quick settings/lock screen or get back into the app interface while the lag is happening, everything is back to normal

Tried to do a screen record but the UI crashes and stops the recording.

### Expected Behavior

The app should work normally without freeze ups when playing songs

### Steps to reproduce

1. Open the app
2. Play any track
3. Move back from Spotube interface to Android UI
4. UI starts to freeze up and lag

### Logs

<details>
<summary>Logs</summary>

```
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-11-26 10:31:30.131448

------- DEVICE INFO -------
id: TQ3C.230901.001.B1
board: kona
bootloader: unknown
brand: Xiaomi
device: aliothin
display: aosp_alioth-userdebug 13 TQ3C.230901.001.B1 3133 release-keys
fingerprint: Xiaomi/aosp_alioth/aliothin:13/TQ3C.230901.001.B1/3133:user/release-keys
hardware: qcom
host: server1
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2012K11AI
product: aosp_alioth
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 3133
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-09-01

------- APP INFO -------
environment: release
version: 3.7.1
appName: Spotube
buildNumber: 32
packageName: oss.krtirtho.spotube

---------- ERROR ----------
OAuth authorization error (invalid_token): The access token expired.

------- STACK TRACE -------
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:268)
<asynchronous suspension>
#6      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:168)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
[2024-11-26 10:37:14.417723]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      SyncedLyricsNotifier.getLRCLibLyrics (package:spotube/provider/spotify/lyrics/synced.dart:58)
<asynchronous suspension>
#2      SyncedLyricsNotifier.build (package:spotube/provider/spotify/lyrics/synced.dart:150)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 10:43:52.258590]---------------------
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:499)
#2      _parseJson (dart:convert-patch/convert_patch.dart:37)
#3      JsonDecoder.convert (dart:convert/json.dart:610)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#6      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#7      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#8      Playlists.get (package:spotify/src/endpoints/playlists.dart:15)
<asynchronous suspension>
#9      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.545583]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#6      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.551792]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:131)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.561819]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#7      FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.562629]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.582813]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
rpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:46:52.583538]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      AlbumReleasesNotifier.fetch (package:spotube/provider/spotify/album/releases.dart:35)
<asynchronous suspension>
#7      AlbumReleasesNotifier.build (package:spotube/provider/spotify/album/releases.dart:50)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:51:19.945857]---------------------
RangeError (length): Invalid value: Valid value range is empty: 1
#0      List.elementAt (dart:core-patch/growable_array.dart)
#1      AudioPlayerStreamListeners.subscribeToPosition.<anonymous closure> (package:spotube/provider/audio_player/audio_player_streams.dart:142)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#8      _DistinctStream._handleData (dart:async/stream_pipe.dart:455)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#10     _rootRunUnary (dart:async/zone.dart:1407)
#11     _CustomZone.runUnary (dart:async/zone.dart:1308)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#14     _DelayedData.perform (dart:async/stream_impl.dart:541)
#15     _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#17     _rootRun (dart:async/zone.dart:1391)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _rootRun (dart:async/zone.dart:1399)
#22     _CustomZone.run (dart:async/zone.dart:1301)
#23     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
d.<anonymous closure> (dart:async/zone.dart:1249)
#28     _rootRun (dart:async/zone.dart:1399)
#29     _CustomZone.run (dart:async/zone.dart:1301)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-11-26 14:53:03.980494]---------------------
RangeError (length): Invalid value: Valid value range is empty: 1
#0      List.elementAt (dart:core-patch/growable_array.dart)
#1      AudioPlayerStreamListeners.subscribeToPosition.<anonymous closure> (package:spotube/provider/audio_player/audio_player_streams.dart:142)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#8      _DistinctStream._handleData (dart:async/stream_pipe.dart:455)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#10     _rootRunUnary (dart:async/zone.dart:1407)
#11     _CustomZone.runUnary (dart:async/zone.dart:1308)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#14     _DelayedData.perform (dart:async/stream_impl.dart:541)
#15     _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#17     _rootRun (dart:async/zone.dart:1391)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _rootRun (dart:async/zone.dart:1399)
#22     _CustomZone.run (dart:async/zone.dart:1301)
#23     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
d.<anonymous closure> (dart:async/zone.dart:1249)
#28     _rootRun (dart:async/zone.dart:1399)
#29     _CustomZone.run (dart:async/zone.dart:1301)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-11-26 14:53:26.757279]---------------------
VideoUnplayableException: Video 'vT1rWIipLK4' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are 
some restrictions in place that prevent watching this video.
Reason: Please sign in
#0      StreamClient._getCipherStream (package:youtube_explode_dart/src/videos/streams/stream_client.dart:179)
<asynchronous suspension>
#1      StreamClient._getStreams (package:youtube_explode_dart/src/videos/streams/stream_client.dart:137)
<asynchronous suspension>
#2      Stream.toList.<anonymous closure> (dart:async/stream.dart:1351)
<asynchronous suspension>
#3      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:37)
<asynchronous suspension>
#4      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:963)
<asynchronous suspension>
#6      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#7      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#8      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#9      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#10     sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#11     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 14:53:41.023950]---------------------
Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1223)
#1      _ButtonsTabBarState.initState.<anonymous closure> (package:buttons_tabbar/buttons_tabbar.dart:197)
#2      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161)
#3      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:912)
#4      Ticker._tick (package:flutter/src/scheduler/ticker.dart:261)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#6      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#8      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238)
#9      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155)
#10     _rootRunUnary (dart:async/zone.dart:1415)
#11     _CustomZone.runUnary (dart:async/zone.dart:1308)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#13     _invoke1 (dart:ui/hooks.dart:330)
#14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397)
#15     _beginFrame (dart:ui/hooks.dart:272)

----------------------------------------
[2024-11-26 14:53:41.032858]---------------------
Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1223)
#1      _ButtonsTabBarState.initState.<anonymous closure> (package:buttons_tabbar/buttons_tabbar.dart:197)
#2      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161)
#3      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:912)
#4      Ticker._tick (package:flutter/src/scheduler/ticker.dart:261)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#6      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#8      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238)
#9      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155)
#10     _rootRunUnary (dart:async/zone.dart:1415)
#11     _CustomZone.runUnary (dart:async/zone.dart:1308)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#13     _invoke1 (dart:ui/hooks.dart:330)
#14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397)
#15     _beginFrame (dart:ui/hooks.dart:272)

----------------------------------------
[2024-11-26 14:53:41.040098]---------------------
Null check operator used on a null value
#0

```
</details>

### Operating System

Android

### Spotube version

3.8.3

### Installation source

GitHub Releases (Binary)

### Additional information

I am on a custom rom with a custom launcher( did try using with the stock launcher)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Kabee2013** [comment]
Same issue for me in spotube android. The app is amazing but because of this bug its horrible to use.

**Comment by Kaidep13** [comment]
@Kabee2013 Are you using a custom rom? Any launchers?

**Comment by Kaidep13** [comment]
@Kabee2013 What device do you have?

**Comment by Kabee2013** [comment]
> @Kabee2013 What device do you have?

samsung a30 Android 11

**Comment by Kaidep13** [comment]
@KRTirtho some help maybe 🥹

**Comment by Kaidep13** [comment]
> > @Kabee2013 What device do you have?
> 
> samsung a30 Android 11, also the downloads never work 

Hey man. I managed to fix it by disabling media cover art on the lockscreen. Check out if this works for you

**Comment by harvind-here** [comment]
Similar to this app crash occurs for me too. I am using latest release apk, tho when I play songs or switch between songs the app halts and doesn't work at all. I have to close the app and reopen again that too after sometime. 😕


May be there is some issue regarding playing track. The song keeps on loading at first when I select to play and then the crash happens as I said before.

**Comment by Apaxa** [comment]
Si. Funciona mal. La vers. 3.9 y la 4.0 en la pantalla Android del coche no funciona bien. No se ve o se queda congelado. Deberían revisar por que no se ve en la pantalla Android del coche. Probé en 2 pantallas diferentes y no funciona. Es una pena por que la aplicación ser es una maravilla
