### ISSUE TITLE
Certain song won't play

### ISSUE THREAD

**Issue by RayBEAMM** [KRTirtho/spotube#2087]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Balloon (feat, Doechii) by Tyler the Creator will not play

### Expected Behavior

The song plays

### Steps to reproduce

1. open the app
2. search Ballon (feat.Doechii)
3. click song to play
4. song presumably will not play

### Logs

```

----------------------------------------
[2024-11-26 19:57:12.289972]---------------------
Option af: dynaudnorm doesn't exist.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-11-26 19:57:12.526216]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:57:12.704844]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#10     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:57:12.739669]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#11     FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:57:12.751901]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#10     SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:57:12.752896]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:57:12.753898]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     AlbumReleasesNotifier.fetch (package:spotube/provider/spotify/album/releases.dart:35)
<asynchronous suspension>
#11     AlbumReleasesNotifier.build (package:spotube/provider/spotify/album/releases.dart:50)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:58:03.482328]---------------------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("__typename")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      transformSectionItemTypeJsonMap (package:spotube/models/spotify/home_feed.dart:174)
#3      transformSectionItemJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:220)
#4      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     Iterable.toList (dart:core/iterable.dart:498)
#11     transformSectionItemJsonMap (package:spotube/models/spotify/home_feed.dart:229)
#12     transformHomeFeedJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:241)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     transformHomeFeedJsonMap (package:spotube/models/spotify/home_feed.dart:244)
#20     CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:164)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:58:03.619022]---------------------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("__typename")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      transformSectionItemTypeJsonMap (package:spotube/models/spotify/home_feed.dart:174)
#3      transformSectionItemJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:220)
#4      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     Iterable.toList (dart:core/iterable.dart:498)
#11     transformSectionItemJsonMap (package:spotube/models/spotify/home_feed.dart:229)
#12     transformHomeFeedJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:241)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     transformHomeFeedJsonMap (package:spotube/models/spotify/home_feed.dart:244)
#20     CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:164)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 19:58:24.471797]---------------------
[TrackNotFoundError] Balloon (feat. Doechii) - Tyler, The Creator, Doechii
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:139)
<asynchronous suspension>
#2      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 20:05:48.327011]---------------------
[TrackNotFoundError] Balloon (feat. Doechii) - Tyler, The Creator, Doechii
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:139)
<asynchronous suspension>
#2      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 20:05:48.329014]---------------------
Failed to open http://localhost:16586/stream/35D1RA5uVFVhMc1qX80TaQ.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-11-26 20:05:53.427894]---------------------
Null check operator used on a null value
#0      AudioPlayerStreamListeners.subscribeToPlaylist.<anonymous closure> (package:spotube/provider/audio_player/audio_player_streams.dart:77)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#9      _rootRunUnary (dart:async/zone.dart:1407)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#15     _DistinctStream._handleData (dart:async/stream_pipe.dart:455)
#16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#17     _rootRunUnary (dart:async/zone.dart:1407)
#18     _CustomZone.runUnary (dart:async/zone.dart:1308)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#21     _DelayedData.perform (dart:async/stream_impl.dart:541)
#22     _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#24     _rootRun (dart:async/zone.dart:1391)
#25     _CustomZone.run (dart:async/zone.dart:1301)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#28     _rootRun (dart:async/zone.dart:1399)
#29     _CustomZone.run (dart:async/zone.dart:1301)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-11-26 20:06:09.754988]---------------------
[TrackNotFoundError] Balloon (feat. Doechii) - Tyler, The Creator, Doechii
#0      PipedSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/piped.dart:68)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:136)
<asynchronous suspension>
#2      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-11-26 20:06:09.754988]---------------------
[MediaKitError] 
Failed to open http://localhost:16586/stream/35D1RA5uVFVhMc1qX80TaQ.
#0      new CustomPlayer.<anonymous closure> (package:spotube/services/audio_player/custom_player.dart:51)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
[2024-11-26 20:06:09.754988]---------------------
Failed to open http://localhost:16586/stream/35D1RA5uVFVhMc1qX80TaQ.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
----------------------------------------
```

### Operating System

Windows 11

### Spotube version

v.3.8.3

### Installation source

Website (spotube.krtirtho.dev)

### Additional information

I even tried to look up he balloon audio on the alternative source track page but only this screen pops up when I search for it 
![image_2024-11-26_201000085](https://github.com/user-attachments/assets/92aaae4d-09ad-4514-b938-73609bf005af)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by keenpaul29** [comment]
kindly assign this issue to me.

**Comment by RayBEAMM** [comment]
> kindly assign this issue to me.

**Comment by keenpaul29** [comment]
Only admin can assign the issue

**Comment by Peperehobbits01** [comment]
> kindly assign this issue to me.

@KRTirtho Seems like someone's want's to help here.

**Comment by NelsonGuiamba** [comment]
a tua Sigla ? (feat. Lila) - Valete, Lila
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:200)
<asynchronous suspension>
#2      SourcedTrackNotifier.build (package:spotube/provider/server/sourced_track.dart:27)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 13:16:29.390541]---------------------
[TrackNotFoundError] Qual é a tua Sigla ? (feat. Lila) - Valete, Lila
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:200)
<asynchronous suspension>
#2      SourcedTrackNotifier.build (package:spotube/provider/server/sourced_track.dart:27)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 13:56:59.278919]---------------------
DioException [connection error]: The connection errored: Failed host lookup: 'open.spotify.com' This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Failed host lookup: 'open.spotify.com' (OS Error: No address associated with hostname, errno = 7)
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      AuthenticationNotifier.credentialsFromCookie (package:spotube/provider/authentication/authentication.dart:111)
<asynchronous suspension>
#2      AuthenticationNotifier.refreshCredentials (package:spotube/provider/authentication/authentication.dart:87)
<asynchronous suspension>

----------------------------------------
[2024-12-09 21:00:42.042210]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#7      FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 21:00:42.170451]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
[2024-12-09 21:00:42.243650]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
m/releases.dart:50)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 21:00:42.268570]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:131)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 21:00:42.396471]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProvide[2024-12-09 21:02:43.323024]---------------------
[TrackNotFoundError] Guilty Conscience 2 - Eminem
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:200)
<asynchronous suspension>
#2      SourcedTrackNotifier.build (package:spotube/provider/server/sourced_track.dart:27)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
Something with some Valete and Eminem songs even 2024 songs on Android but they play on Spotify
