### ISSUE TITLE
App crashes after pressing back button on hanging search results

### ISSUE THREAD

**Issue by nandotiamat** [KRTirtho/spotube#2104]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When going to the search page, searching a song and without selecting anything **changing menu** from the bottom navigation bar (easy to do on desktop, on android it's needed to hide the keyboard), the search results don't disappear and you can't interact with any of them, if the back button is pressed, the app crashes.

### Expected Behavior

The search window should appear only in the search page

### Steps to reproduce

1. open Spotube
2. go to the search page
3. search anything
4. without selecting anything, change page via the bottom navigation bar
5. press the back button in the hanging search results window

### Logs

<details>
<summary>Logs</summary>

```----------------------------------------
[2024-12-03 00:28:17.755220]---------------------
Null check operator used on a null value
#0      _SearchViewRoute.didPop (package:flutter/src/material/search_anchor.dart:561)
#1      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:3167)
#2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4340)
#3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5368)
#4      _ViewContentState.build.<anonymous closure> (package:flutter/src/material/search_anchor.dart:871)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
#18     _rootRunUnary (dart:async/zone.dart:1415)
#19     _CustomZone.runUnary (dart:async/zone.dart:1308)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#21     _invoke1 (dart:ui/hooks.dart:330)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

----------------------------------------
```
</details>

### Operating System

Arch Linux, Android

### Spotube version

v3.8.3

### Installation source

Play Store (Android), Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by ghagevaibhav** [comment]
also, when the keyboard is open the back button seems to not work.

**Comment by passionroro** [comment]
I'm experiencing the same crash on macos. Logs are the same. 

Operating System: macOS
Spotube version: 3.9.0
Installation source: [dmg file](https://github.com/KRTirtho/Spotube/releases/latest/download/Spotube-macos-universal.dmg)
