### ISSUE TITLE
invidious type 'null; bug linux flatpak

### ISSUE THREAD

**Issue by s-b-repo** [KRTirtho/spotube#2121]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

type 'null' is not a subtype of string in type cast 

### Expected Behavior

select instance

### Steps to reproduce

changed source

### Logs

<details>
<summary>Logs</summary>
[2024-12-09 12:46:55.749039]---------------------
org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.freedesktop.Avahi.service not found.
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1149)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:621)
<asynchronous suspension>
#2      AvahiServer.callGetVersionString (package:bonsoir_linux/src/avahi/server.dart:95)
<asynchronous suspension>
#3      AvahiBonsoirDiscovery._isModernAvahi (package:bonsoir_linux/src/actions/discovery/discovery.dart:323)
<asynchronous suspension>
#4      AvahiBonsoirDiscovery.ready (package:bonsoir_linux/src/actions/discovery/discovery.dart:49)
<asynchronous suspension>
#5      ConnectClientsNotifier.build (package:spotube/provider/connect/clients.dart:37)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:46:55.929334]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:47:00.209076]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:47:11.335018]---------------------
type 'Null' is not a subtype of type 'String' in type cast
#0      _$$InvidiousMonitorImplFromJson (package:invidious/src/models/model.g.dart:493)
#1      new _$InvidiousMonitorImpl.fromJson (package:invidious/src/models/model.freezed.dart:5728)
#2      _$InvidiousMonitorFromJson (package:invidious/src/models/model.freezed.dart:5309)
#3      new InvidiousMonitor.fromJson (package:invidious/src/models/responses/instance.dart:128)
#4      _$$InvidiousInstanceDetailsImplFromJson (package:invidious/src/models/model.g.dart:361)
#5      new _$InvidiousInstanceDetailsImpl.fromJson (package:invidious/src/models/model.freezed.dart:4092)
#6      _$InvidiousInstanceDetailsFromJson (package:invidious/src/models/model.freezed.dart:3858)
#7      new InvidiousInstanceDetails.fromJson (package:invidious/src/models/responses/instance.dart:28)
#8      _$$InvidiousInstanceResponseImplFromJson (package:invidious/src/models/model.g.dart:336)
#9      new _$InvidiousInstanceResponseImpl.fromJson (package:invidious/src/models/model.freezed.dart:3792)
#10     _$InvidiousInstanceResponseFromJson (package:invidious/src/models/model.freezed.dart:3668)
#11     new InvidiousInstanceResponse.fromJson (package:invidious/src/models/responses/instance.dart:11)
#12     InstancesEndpoint.instances.<anonymous closure> (package:invidious/src/endpoints/instances.dart:13)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     InstancesEndpoint.instances (package:invidious/src/endpoints/instances.dart:17)
<asynchronous suspension>
#20     invidiousInstancesProvider.<anonymous closure> (package:spotube/provider/audio_player/sources/invidious_instances_provider.dart:7)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:50:14.580748]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:50:17.181295]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:50:19.863650]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-09 12:50:19.864025]---------------------
PathNotFoundException: Cannot open file, path = '/home/kali/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------

</details>

### Operating System

linux

### Spotube version

latest

### Installation source

Flathub (Flatpak)

### Additional information

nothing 

### Self grab

- [X] I'm ready to work on this issue!

**Comment by CodingByMe** [comment]
Also on Windows 10

**Comment by Anjolao** [comment]
The invidious instances is all having errors.
