### ISSUE TITLE
Spotube triggers continuous warnings about Spotify API rate being exceeded

### ISSUE THREAD

**Issue by callegar** [KRTirtho/spotube#2126]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

While running spotube the console gets multiple messages such as:
flutter: Spotify API rate exceeded. waiting for 6 seconds
Unclear if this is just some debugging or if there is an actual issue in how spotube uses the spotifiy API.

### Expected Behavior

If this is just innocuous debugging it should probably be hidden behind a --debug option. Otherwise usage of the Spotify API should not produce errors.

### Steps to reproduce

1. Opened the app
2. searched for an artist
3. started to play a playlist
4. got the repeated messages on the console.

### Logs

N/A

### Operating System

Linux

### Spotube version

3.9.0

### Installation source

Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by fbgeobit** [comment]
Same issue for me.
It could be a limitation established by Spotify?

Log ouput when it occurs.
```----------------------------------------
[2024-12-26 13:48:52.255224]---------------------
Error Code: 429
API rate limit exceeded
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:279)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#4      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------```

OS: Debian 12, X11

**Comment by Tbnrtanishq** [comment]
Hey I am having a problem 
Error Authentication Failure

DioException [bad response]: This exception was thrown because the response has a status code of 429 and RequestOptions.validateStatus was configured to throw for this status code.

The status code of 429 has the following meaning: "Client error the request contains bad syntax or cannot be fulfilled"

Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code

How do I fix that?

**Comment by Killercoder07** [comment]
I am also having this problem. It was working alright yesterday, but suddenly I have also started to get this error.
Any solution for this?

**Comment by Freebase394** [comment]
On this last week there is a lot of error related to this issues
