### ISSUE TITLE
Logged in Screen and Error Authentication Failure

### ISSUE THREAD

**Issue by czl92783719** [KRTirtho/spotube#2129]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

After logged in there showed a logged in screen instead of redirected to Spotube's homepage, and after seconds shows an Error Authentication Failure screen

### Expected Behavior

Go to the homepage

### Steps to reproduce

1. Open the app
2. Log into Spotify account
3. 
![Screenshot_20241212-155943_Spotube](https://github.com/user-attachments/assets/dc8cea47-1ec7-40f8-92ba-44d0d7c47578)
![Screenshot_20241212-160807_Spotube](https://github.com/user-attachments/assets/620d85fc-620e-4cc2-b327-3feb35c94460)

### Logs

<details>
<summary>Logs</summary>

```
/rendering/object.dart:1098)
#767    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719)
#768    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278)
#769    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369)
#770    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#771    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
#772    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1092)
#773    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
#774    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
#775    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#776    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#777    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#778    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#779    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1448)
#780    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#781    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#782    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#783    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#784    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#785    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#786    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#787    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#788    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#789    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#790    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#791    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#792    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#793    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#794    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#795    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#796    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#797    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#798    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#799    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3726)
#800    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#801    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111)
#802    RenderObject.layout (package:flutter/src/rendering/object.dart:2608)
#803    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1002)
#804    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1311)
#805    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446)
#806    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052)
#807    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065)
#808    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602)
#809    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164)
#810    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#811    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#812    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#813    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#814    _rootRun (dart:async/zone.dart:1399)
#815    _CustomZone.run (dart:async/zone.dart:1301)
#816    _CustomZone.runGuarded (dart:async/zone.dart:1209)
#817    _invoke (dart:ui/hooks.dart:314)
#818    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#819    _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------
[2024-12-12 16:10:38.927320]---------------------
ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = accounts.spotify.com, port = 43178, uri=https://accounts.spotify.com/api/token
#0      IOClient.send (package:http/src/io_client.dart:154)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:71)
<asynchronous suspension>

----------------------------------------
[2024-12-12 16:10:41.071314]---------------------
ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = accounts.spotify.com, port = 43178, uri=https://accounts.spotify.com/api/token
#0      IOClient.send (package:http/src/io_client.dart:154)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:71)
<asynchronous suspension>

----------------------------------------

```
</details>

### Operating System

Android 14 (LineageOS 21)

### Spotube version

3.8.3

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by czl92783719** [comment]
Same issue on my Spotube 3.9.0 Flatpak on Debian GNU/Linux Sid
```
onvert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#10     SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
er/spotify/album/releases.dart:50)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:39:40.501439]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#11     FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:39:40.502511]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#10     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:39:47.891511]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:19.810755]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:19.810922]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:23.234835]---------------------
No track currently
#0      SyncedLyricsNotifier.build (package:spotube/provider/spotify/lyrics/synced.dart:131)
<asynchronous suspension>
#1      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:23.240143]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:23.937358]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:23.939770]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:24.177673]---------------------
Error Code: 401
Valid user authentication required
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#4      FavoritePlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/favorite.dart:33)
<asynchronous suspension>
#5      FavoritePlaylistsNotifier.build (package:spotube/provider/spotify/playlist/favorite.dart:44)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:24.999997]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-12 20:40:25.000037]---------------------
PathNotFoundException: Cannot open file, path = '/home/czl92783719/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------

```

**Comment by czl92783719** [comment]
![image](https://github.com/user-attachments/assets/cb6b63fc-38d8-4b99-8051-81fada7ea12c)
