### ISSUE TITLE
Crash whenever I open the keyboard to log into Spotify.

### ISSUE THREAD

**Issue by fedes1to** [KRTirtho/spotube#2157]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Crash whenever I open the keyboard to log into Spotify. I tested this on other input fields on the app and they worked just fine.

### Expected Behavior

To not crash and be able to log in.

### Steps to reproduce

1. Open the app
2. Open Settings
3. Click on "Login with your Spotify account"
4. Try to enter the e-mail
5. Crash

### Logs

<details>
<summary>Logs</summary>

```
2024-12-18 13:19:23.288 21881-4382  libc                    usap64                               A  Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x70305e776c in tid 4382 (HeapTaskDaemon), pid 21881 (rtirtho.spotube)
2024-12-18 13:19:23.372  2011-2885  ImeTracker              system_server                        I  oss.krtirtho.spotube:5410c782: onRequestHide at ORIGIN_SERVER reason HIDE_REMOVE_CLIENT fromUser false
2024-12-18 13:19:23.372  2011-14477 WindowManager           system_server                        I  WIN DEATH: Window{ab40a31 u0 oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity}
2024-12-18 13:19:23.372  2011-3436  MediaSessionStack       system_server                        I  removeSession | record: oss.krtirtho.spotube/media-session/77 (userId=0)
2024-12-18 13:19:23.372  2011-14477 InputManager-JNI        system_server                        W  Input channel object 'ab40a31 oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity (client)' was disposed without first being removed with the input manager!
2024-12-18 13:19:23.373  2011-3436  MediaSessionService     system_server                        D  destroySessionLocked: record=oss.krtirtho.spotube/media-session/77 (userId=0)
2024-12-18 13:19:23.373  2011-3188  serviceDiscovery        system_server                        I  [MdnsDiscoveryManager] Unregistering listener for serviceType:_spotube._tcp.local
2024-12-18 13:19:23.373  2011-10002 ActivityManager         system_server                        I  Process oss.krtirtho.spotube (pid 21881) has died: fg  TOP 
2024-12-18 13:19:23.383  2011-10002 ActivityManager         system_server                        W  Exception when unbinding service oss.krtirtho.spotube/org.chromium.content.app.SandboxedProcessService0:0
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:586)
                                                                                                    	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1463)
                                                                                                    	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:6670)
                                                                                                    	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:7217)
                                                                                                    	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:13808)
                                                                                                    	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3437)
                                                                                                    	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3558)
                                                                                                    	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1623)
                                                                                                    	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:333)
                                                                                                    	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:726)
2024-12-18 13:19:23.384  2011-10002 ActivityTaskManager     system_server                        W  Force removing ActivityRecord{a5c1392 u0 oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity t741}: app died, no saved state
2024-12-18 13:19:23.386 10005-10021 WindowManagerShell      com.android.systemui                 V  Transition requested (#958): android.os.BinderProxy@25362c5 TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=741 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity } baseActivity=ComponentInfo{oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity} topActivity=ComponentInfo{oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity} origActivity=null realActivity=ComponentInfo{oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity} numActivities=1 lastActiveTime=77179493 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@ef7441a} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 94 - 0, 0) topActivityInfo=ActivityInfo{c241b4b com.ryanheise.audioservice.AudioServiceActivity} launchCookies=[android.os.BinderProxy@af0149d] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= falseisLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2400 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatTaskInfo=CameraCompatTaskInfo { cameraCompatControlState=hidden freeformCameraCompatMode=inactive}}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 958 }
2024-12-18 13:19:23.402  2011-3436  ImeTracker              system_server                        I  oss.krtirtho.spotube:5410c782: onFailed at PHASE_SERVER_APPLY_IME_VISIBILITY

```
</details>

### Operating System

Android

### Spotube version

v3.9.0

### Installation source

F-Droid (Android)

### Additional information

I tried different Input Methods and also different Installations sources, all gave same issue. Also the logs are from logcat.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by fedes1to** [comment]
Also note that I am on Android 15 (might be related I don't know)

**Comment by fedes1to** [comment]
Updated to v4.0.0, issue is still happening
