### ISSUE TITLE
Website text wrap on login page on wayland

### ISSUE THREAD

**Issue by Gater73** [KRTirtho/spotube#2163]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When you click "Login with Spotify" the website is rendered with all text wrapping up in a vertical way as if the total screen width was low. 
![image](https://github.com/user-attachments/assets/35d52174-5e70-406e-8373-5607ac8e2445)

### Expected Behavior

The website should be rendered properly.

### Steps to reproduce

1. Open spotube in KDE using wayland (flatpak version)
2. Click the Setting icon
3. Click "Login with Spotify"

### Logs

<details>
<summary>Logs</summary>

Flatpak logs:
```
[whoami@whoamilinux ~]$ flatpak run com.github.KRTirtho.Spotube

** (spotube:2): CRITICAL **: 01:48:43.725: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:43.726: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:43.726: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:43.727: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:43.727: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

** (spotube:2): CRITICAL **: 01:48:46.962: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:46.963: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:46.963: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:46.963: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:2): CRITICAL **: 01:48:46.964: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
~WebviewWindow

(spotube:2): GLib-GObject-CRITICAL **: 01:48:56.885: ../gobject/gsignal.c:2685: instance '0x37bfbd22230' has no handler with id '493'

```
Spotube logs:
```
dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#11     FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-20 01:49:39.459586]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Me.get (package:spotify/src/endpoints/me.dart:22)
<asynchronous suspension>
#10     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
m/releases.dart:50)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-20 01:49:40.467911]---------------------
PathNotFoundException: Cannot open file, path = '/home/whoami/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-20 01:49:44.965942]---------------------
PathNotFoundException: Cannot open file, path = '/home/whoami/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-20 01:49:52.599455]---------------------
PathNotFoundException: Cannot open file, path = '/home/whoami/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------
[2024-12-20 01:49:52.599541]---------------------
PathNotFoundException: Cannot open file, path = '/home/whoami/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#4      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#5      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#6      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#7      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#8      GSettings.get (package:gsettings/src/gsettings.dart:124)
<asynchronous suspension>
#9      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>
#10     _RawDecoratedTitlebarButtonState.initState.<anonymous closure> (package:titlebar_buttons/src/decorated_button.dart:156)
<asynchronous suspension>

----------------------------------------


```
</details>

### Operating System

Arch Linux (Kernel 6.12.4-arch1-1)

### Spotube version

3.9.0

### Installation source

Flathub (Flatpak)

### Additional information

OS: Arch Linux x86_64
Kernel: 6.12.4-arch1-1 
DE: Plasma 6.2.4
CPU: AMD Ryzen 5 5600X (12) @ 4.651GHz
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT
Using Wayland

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by lucyamonster** [comment]
I'm having the same issue, But the wrapping isn't at the end:
![Image](https://github.com/user-attachments/assets/6a78127a-abc8-403f-b686-e63be865f9e0)
Kde + wayland on arch.

**Comment by natwat123** [comment]
I'm having the same issue on nixos with plasma 6.
