### ISSUE TITLE
Error logging into Spotify

### ISSUE THREAD

**Issue by YY-8885** [KRTirtho/spotube#2164]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Error logging into Spotify
![1](https://github.com/user-attachments/assets/777db396-35fb-4768-9e94-fc757fed8ff6)
![2](https://github.com/user-attachments/assets/9fd3063f-9e35-4722-b109-0d13adfeea38)

### Expected Behavior

Cannot display any songs

### Logs

[2024-12-20 13:35:13.103398]---------------------
DioException [connection error]: The connection errored: 信号灯超时时间已到
 This indicates an error which most likely cannot be solved by the library.
Error: SocketException: 信号灯超时时间已到
 (OS Error: 信号灯超时时间已到
, errno = 121), address = open.spotify.com, port = 5761
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      AuthenticationNotifier.credentialsFromCookie (package:spotube/provider/authentication/authentication.dart:111)
<asynchronous suspension>
#2      AuthenticationNotifier.login (package:spotube/provider/authentication/authentication.dart:96)
<asynchronous suspension>
#3      useLoginCallback.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:spotube/pages/mobile_login/hooks/login_callback.dart:55)
<asynchronous suspension>

----------------------------------------

### Operating System

windows 11

### Spotube version

3.9.0

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by liaoleyuan** [comment]
I've met the same issue.

**Comment by liaoleyuan** [comment]
I've met the same issue.
When I click "CONNECT WITH SPOTIFY" button, it just pop up that logining web page. 
What's next? I can't find the UI to input the sp_dc and sp_key.

**Comment by s-b-repo** [comment]
https://nomusica.com/spotify-api-changes-developers-lose-access-to-key-data/ updated api

**Comment by 15582472344** [comment]
这个问题解决了吗，我遇到了同样的问题，

![Image](https://github.com/user-attachments/assets/8d91ccf5-a7a3-4502-acdb-1622118e05a7)

**Comment by ZZZZzzzzac** [comment]
same problem here, there is no `4. You will be asked to grant Spotube permission to access your Spotify account. Click on the “Agree” button to grant permission.`
