### ISSUE TITLE
Search Tab crashes entire app after playing a song

### ISSUE THREAD

**Issue by J0nathan550** [KRTirtho/spotube#2200]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When I start to play something from the library and then go to search the search tab become soft locked and crashes the interface leaving only audio to play.

### Expected Behavior

Just close the search tab and move along

### Steps to reproduce

1. Go to library
2. Start playing any library music, wait until it will do sound
3. Go to search tab
4. Start searching
5. Try to go to different page
6. The search tab will soft lock the view and if you click escape the entire interface will crash leaving only tray

### Logs

----------------------------------------
[2024-12-30 17:27:24.707352]---------------------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("__typename")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      transformSectionItemTypeJsonMap (package:spotube/models/spotify/home_feed.dart:174)
#3      transformSectionItemJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:220)
#4      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     Iterable.toList (dart:core/iterable.dart:498)
#11     transformSectionItemJsonMap (package:spotube/models/spotify/home_feed.dart:229)
#12     transformHomeFeedJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:241)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     transformHomeFeedJsonMap (package:spotube/models/spotify/home_feed.dart:244)
#20     CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:164)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------
[2024-12-30 17:27:48.976380]---------------------
Null check operator used on a null value
#0      _SearchViewRoute.didPop (package:flutter/src/material/search_anchor.dart:561)
#1      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:3167)
#2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4340)
#3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5368)
#4      LocalFolderCacheExportDialog.build.<anonymous closure> (package:spotube/modules/library/local_folder/cache_export_dialog.dart:109)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
#18     _rootRunUnary (dart:async/zone.dart:1415)
#19     _CustomZone.runUnary (dart:async/zone.dart:1308)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#21     _invoke1 (dart:ui/hooks.dart:330)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

----------------------------------------
[2024-12-30 17:31:15.816306]---------------------
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("__typename")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      transformSectionItemTypeJsonMap (package:spotube/models/spotify/home_feed.dart:174)
#3      transformSectionItemJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:220)
#4      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     Iterable.toList (dart:core/iterable.dart:498)
#11     transformSectionItemJsonMap (package:spotube/models/spotify/home_feed.dart:229)
#12     transformHomeFeedJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:241)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     transformHomeFeedJsonMap (package:spotube/models/spotify/home_feed.dart:244)
#20     CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:164)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>

----------------------------------------

### Operating System

Windows (11)

### Spotube version

3.9.0

### Installation source

GitHub Releases (Binary)

### Additional information

https://github.com/user-attachments/assets/04e66aa7-2c48-468d-a5b4-ca63b31812ab

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by MarcosBL** [comment]
+1 here, in Linux Mint with the deb install :+1:

**Comment by bawsuser** [comment]
had the same problem but was marked as duplicate the dev said its some kind of flutter problem.
