### ISSUE TITLE
[Bug] Black screen when clicking on any text input component

### ISSUE THREAD

**Issue by BapRx** [KRTirtho/spotube#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on any text input component, the whole screen goes black, including the navigation bar.

The application is still responsive, I can see the mouse cursor go from the point shape to the hand shape when it goes over a button. The music continues playing like nothing happened. I can interact with the buttons, input, etc. for example I was able to login despite the black screen by remembering the element position.

This issue might be related to #279 even though I'm running Spotube on Linux, installed with Flatpak.

I ran the app with the debug flags but the app doesn't log anything when the problem occurs.

<details>
  <summary>Debug logs</summary>

```
❯ ERROR=true VERBOSE=true DEBUG=true flatpak run com.github.KRTirtho.Spotube -v
Gtk-Message: 17:18:28.581: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:18:28.582: Failed to load module "canberra-gtk-module"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = /var/run/dbus/system_bus_socket, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:948)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1815)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21)
#4      DBusClient._openSocket (package:dbus/src/dbus_client.dart:767)
#5      DBusClient._connect (package:dbus/src/dbus_client.dart:787)
#6      DBusClient.callMethod (package:dbus/src/dbus_client.dart:607)
#7      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:448)
#8      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:624)
#9      DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:131)
#10     _runGuarded (dart:async/stream_controller.dart:814)
#11     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207)
#12     _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
#13     _StreamImpl.listen (dart:async/stream_impl.dart:471)
#14     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:124)
#15     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114)
#16     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86)
#17     _ForwardingStream.listen (dart:async/stream_pipe.dart:81)
#18     NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2303)
#19     ConnectivityLinux._startListenConnectivity (package:connectivity_plus_linux/src/connectivity.dart:61)
#20     _runGuarded (dart:async/stream_controller.dart:814)
#21     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207)
#22     _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
#23     _StreamImpl.listen (dart:async/stream_impl.dart:471)
#24     new QueryBowl (package:fl_query/src/query_bowl.dart:91)
#25     bowl (package:spotube/main.dart:28)
#26     new _GrowableList._literal2 (dart:core-patch/growable_array.dart)
#27     main.<anonymous closure> (package:spotube/main.dart:58)
#28     HookBuilder.build (package:flutter_hooks/src/framework.dart:621)
#29     StatelessElement.build (package:flutter/src/widgets/framework.dart:4949)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#36     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195)
#37     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164)
#38     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111)
#39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605)
#40     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110)
#41     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945)
#42     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925)
#43     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420)
#44     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#45     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
```
</details>

I didn't find a way to go back from the black screen, I have to kill the app and start it again.

### Expected Behavior

Not a black screen.

### Steps To Reproduce

1. Open Spotube
2. Click `Search` on the left panel
3. Click on the text input on top of the screen
4. *Lights out*

### Spotube Version

v2.5.0

### Operating System

Linux

### Linux Distribution (if applicable)

Ubuntu 

### Operating System Version

22.04 / 22.10

### Installation Source

Flathub (Flatpak)

### Additional information

The drop-down input work as expected.

The folder selection button used to change the download location doesn't seem to work but doesn't trigger the black screen.

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/32563450/203370591-befedd3a-5bc1-41ea-8a7c-40e11f1113c5.png)

</details>

Thank you! :slightly_smiling_face:

**Comment by KRTirtho** [comment]
Can you try with the nightly version?

**Comment by KRTirtho** [comment]
Or uninstall and re-install

**Comment by BapRx** [comment]
I have the same issue with `Spotube v2.5.0-nightly-69`

**Comment by BapRx** [comment]
Also the bug is triggered either by clicking or accessing the input using the `tab` key.

**Comment by BapRx** [comment]
Still experiencing this issue with the latest version v2.6.0

**Comment by BapRx** [comment]
Hey @KRTirtho I'm happy to say the latest release fixed the issue! Thanks :smile:

**Comment by willfulpeople** [comment]
![image](https://github.com/KRTirtho/spotube/assets/47940701/535538ba-0e5e-41e9-8eab-0893dcb5e327)
