### ISSUE TITLE
[Bug] System crashes instantly when Spotube is launched.

### ISSUE THREAD

**Issue by MrBallade** [KRTirtho/spotube#403]
### UPDATE
I randomly tried to open Spotube one evening and it opened! However, it remained unusable. 
Opening it from the terminal immediately yields the following:

```
** (spotube:17472): CRITICAL **: 22:26:13.091: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
** (spotube:17472): CRITICAL **: 22:26:13.093: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
```

but the window still appeared and I was able to log in. However, after clicking on Songs, Spotube crashed again, now with a new message:

```
spotube: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion 'kref' failed.
```

When attempting to relaunch the application, it again crashes immediately with the following message:

<details>
  <summary>
    <b> WARNING: LONG</b>
  </summary>

```
** (spotube:18669): CRITICAL **: 22:38:01.258: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
** (spotube:18669): CRITICAL **: 22:38:01.260: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
AudioPlayers: Could not query current duration.
AudioPlayers: Could not query current duration.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Concurrent modification during iteration: _LinkedHashSet len:4.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:706)
#1      new QueryBowl.<anonymous closure> (package:fl_query/src/query_bowl.dart:98)
<asynchronous suspension>
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch8: krec 0 pushes 2 bufs 19 relocs 0
nouveau: ch8: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch8: buf 00000001 00000006 00000004 00000000 00000004
nouveau: ch8: buf 00000002 0000002d 00000002 00000002 00000002
nouveau: ch8: buf 00000003 0000002e 00000004 00000004 00000000
nouveau: ch8: buf 00000004 0000002f 00000002 00000000 00000002
nouveau: ch8: buf 00000005 00000030 00000004 00000004 00000000
nouveau: ch8: buf 00000006 00000031 00000004 00000004 00000000
nouveau: ch8: buf 00000007 00000032 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch8: krec 0 pushes 2 bufs 18 relocs 0
nouveau: ch8: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch8: buf 00000001 00000006 00000004 00000000 00000004
nouveau: ch8: buf 00000002 0000000e 00000002 00000002 00000002
nouveau: ch8: buf 00000003 0000002d 00000004 00000004 00000000
nouveau: ch8: buf 00000004 0000002c 00000002 00000000 00000002
nouveau: ch8: buf 00000005 0000002e 00000004 00000004 00000000
nouveau: ch8: buf 00000006 00000030 00000004 00000004 00000000
nouveau: ch8: buf 00000007 0000000a 00000002 00000002 00000002
nouveau: ch8: buf 00000008 00000008 00000002 00000002 00000000
nouveau: ch8: buf 00000009 0000000c 00000002 00000000 00000002
nouveau: ch8: buf 0000000a 00000007 00000002 00000002 00000000
nouveau: ch8: buf 0000000b 0000000f 00000004 00000004 00000000
nouveau: ch8: buf 0000000c 00000031 00000004 00000004 00000000
nouveau: ch8: buf 0000000d 00000032 00000004 00000004 00000000
nouveau: ch8: buf 0000000e 00000033 00000004 00000004 00000000
nouveau: ch8: buf 0000000f 00000034 00000004 00000004 00000000
nouveau: ch8: buf 00000010 00000035 00000004 00000004 00000000
nouveau: ch8: buf 00000011 00000036 00000004 00000004 00000000
nouveau: ch8: psh 00000000 000002febc 0000030474
nouveau: 	0x200181c2
nouveau: 	0x03303210
nouveau: 	0x200681c3
nouveau: 	0x00001040
nouveau: 	0x000003fc
nouveau: 	0x000002bc
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20088100
nouveau: 	0x00000000
nouveau: 	0x072ba000
nouveau: 	0x00000000
nouveau: 	0x06800000
nouveau: 	0x00000ff0
nouveau: 	0x00001000
nouveau: 	0x000003fc
nouveau: 	0x000002bc
nouveau: 	0x200180c0
nouveau: 	0x00000686
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000040
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x000000c8
nouveau: 	0x000000c8
nouveau: 	0x00000000
nouveau: 	0x066d0000
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000400
nouveau: 	0x000000c8
nouveau: 	0x000000c8
nouveau: 	0x00000000
nouveau: 	0x00790000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x000000c8
nouveau: 	0x000000c8
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000040
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000064
nouveau: 	0x00000064
nouveau: 	0x00000000
nouveau: 	0x06704000
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000200
nouveau: 	0x00000064
nouveau: 	0x00000064
nouveau: 	0x00000000
nouveau: 	0x048b0000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000064
nouveau: 	0x00000064
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20024062
nouveau: 	0x00000000
nouveau: 	0x00771ac0
nouveau: 	0x20024060
nouveau: 	0x00000020
nouveau: 	0x00000001
nouveau: 	0xa009406c
nouveau: 	0x00001001
nouveau: 	0x54e24908
nouveau: 	0x06800000
nouveau: 	0x00600000
nouveau: 	0x00070020
nouveau: 	0xe88003fb
nouveau: 	0x800002bb
nouveau: 	0x03000000
nouveau: 	0x00000000
nouveau: 	0x200104cd
nouveau: 	0x00000000
nouveau: 	0x200308e0
nouveau: 	0x00010000
nouveau: 	0x00000000
nouveau: 	0x00740000
nouveau: 	0x200208e3
nouveau: 	0x00000020
nouveau: 	0x000000d6
nouveau: 	0x20030700
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x00019200
nouveau: 	0x200207c0
nouveau: 	0x00000000
nouveau: 	0x0001925f
nouveau: 	0x20030704
nouveau: 	0x00001010
nouveau: 	0x00000000
nouveau: 	0x00019208
nouveau: 	0x200207c2
nouveau: 	0x00000000
nouveau: 	0x0001925f
nouveau: 	0x20010586
nouveau: 	0x00000004
nouveau: 	0x2002035d
nouveau: 	0x00000000
nouveau: 	0x00000006
nouveau: 	0x80000585
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000030
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000032
nouveau: 	0x00000032
nouveau: 	0x00000000
nouveau: 	0x06712000
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000032
nouveau: 	0x00000032
nouveau: 	0x00000000
nouveau: 	0x007f9000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000032
nouveau: 	0x00000032
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000020
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000019
nouveau: 	0x00000019
nouveau: 	0x00000000
nouveau: 	0x06716000
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000019
nouveau: 	0x00000019
nouveau: 	0x00000000
nouveau: 	0x00615000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000019
nouveau: 	0x00000019
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000010
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x0000000c
nouveau: 	0x0000000c
nouveau: 	0x00000000
nouveau: 	0x06717000
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x0000000c
nouveau: 	0x0000000c
nouveau: 	0x00000000
nouveau: 	0x007f0000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x0000000c
nouveau: 	0x0000000c
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x06717400
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x007f1000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x06717600
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x007fd000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000001
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x06717800
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000001
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x007fe000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000001
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200406c0
nouveau: 	0x00000000
nouveau: 	0x00014000
nouveau: 	0x00000057
nouveau: 	0x1000f010
nouveau: kernel rejected pushbuf: No such device
nouveau: ch8: krec 0 pushes 2 bufs 2 relocs 0
nouveau: ch8: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch8: buf 00000001 00000006 00000004 00000000 00000004
nouveau: ch8: psh 00000000 0000030c20 0000030cb4
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: kernel rejected pushbuf: No such device
nouveau: ch8: krec 0 pushes 2 bufs 2 relocs 0
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: ch8: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch8: buf 00000001 00000006 00000004 00000000 00000004
nouveau: ch8: psh 00000000 0000030c20 0000030cb4
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x067c7400
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x00615000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: ch8: psh 00000000 0000030cb4 0000030d34
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x067c7600
nouveau: 	0x800060ae
nouveau: 	0x20046086
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x067c7400
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x00000000
nouveau: 	0x00615000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000006
nouveau: 	0x00000006
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: ch8: psh 00000000 0000030cb4 0000030d34
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x067c7600
nouveau: 	0x800060ae
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x00616000
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000100
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x00000000
nouveau: 	0x00616000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000003
nouveau: 	0x00000003
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
spotube: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion 'kref' failed.
Aborted
```
</details> 

--------

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Instantly, when Spotube is launched, the screen freezes and the system crashes, resulting in a system logout.
The window does seem to open, but there often isn't enough time for it to completely go full-screen.
This happens with a fresh install without any warnings or errors.

### Expected Behavior

The Spotube window opens normally and can be used without causing a system crash.

### Steps To Reproduce

Download and install Spotube-linux-x86_64.deb
Launch Spotube
.. crash

### Spotube Version

v2.6.0

### Operating System

Linux

### Linux Distribution (if applicable)

Debian

### Operating System Version

11

### Installation Source

Github Release (Binary)

### Additional information

I'm using GNOME as my DE.

**Comment by KRTirtho** [comment]
Check your driver configuration. This is probably due to an unfinished driver installation

**Comment by MrBallade** [comment]
There does not seem to be any issues with the driver instillation, so it might be caused Flutter, as the situation seems similar to the issue you referred to. Is there any way to work around this issue? Preferably, one that doesn't involve installing a proprietary driver.

**Comment by KRTirtho** [comment]
Unfortunately, I don't know any workaround for this. The best I can suggest is to use proprietary drivers to check if it happens in that situation too just confirm what is actually causing the issue

**Comment by MrBallade** [comment]
Yes! I now works, although it did require me to change my system to Debian 12, which is still in testing, as the instillation depended on a newer version of libc6 - GLIBC.

**Comment by KRTirtho** [comment]
Yeah, libapp.so which is the pure dart binary of a flutter app depends on libc6 or higher

**Comment by MrBallade** [comment]
I understand. I have been using Spotube 2.7.0 for about a day now, and the issue first at hand is no longer reproduced.
