### ISSUE TITLE
Spotube stops playing the next song after it finishes the current one

### ISSUE THREAD

**Issue by hanweikung** [KRTirtho/spotube#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes when the end of the current song is reached, Spotube does not move on to the next track. It appears stuck at the end of the current song.

### Expected Behavior

Playback continues after each song.

### Steps to reproduce

1. Play a song (for example, https://open.spotify.com/track/2cDgEcL6Q0lFt1PjuW8ljA) and wait until it ends. 
2. The next song is not played.

### Operating System

Ubuntu 22.04

### Spotube version

v3.0.0

### Installation source

Flathub (Flatpak)

### Additional information

Information from my .spotube_logs

```bash
============================== CATCHER LOG ==============================
Crash occurred on 2023-07-15 13:53:36.133773

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.0.0
appName: spotube
buildNumber: 19
packageName: spotube

---------- ERROR ----------
HandshakeException: Connection terminated during h
------- S------- STACK TRACE#0      I
------- CUSTOM INFO -------
======================================================================
kage:oauth2/src/client.dart:114)
<asynchronous suspension>
#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#3      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:173)
<asynchronous suspension>
#4      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:206)
<asynchronous suspension>
#5      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:172)
<asynchronous suspension>
#6      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```

**Comment by FedericoSlongo** [comment]
I have the same problem but on windows

**Comment by vokf** [comment]
I have the same problem but on Android

**Comment by KRTirtho** [comment]
Is it any better in v3.0.1

**Comment by hanweikung** [comment]
I tried the flatpak version of v3.0.1 on Ubuntu 22.04. The problem occurred again when I played this song https://open.spotify.com/track/1vdg4IQBVuXobdkaacGTPv

Here is my .spotube_logs if it helps.

```bash
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-06 17:26:08.359121

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.0.1
appName: spotube
buildNumber: 20
packageName: spotube

---------- ERROR ----------
PathNotFoundException: Cannot open file, path = '/home/hanwei/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#5      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#6      GSettings.get (package:gsettings/src/gsettings.dart:117)
<asynchronous suspension>
#7      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```

**Comment by xididri** [comment]
Same bug on v3.0.1 on Windows 11

**Comment by KRTirtho** [comment]
Try the latest nightly. There was a fix applied

**Comment by xididri** [comment]
I cannot play any songs on this version (Spotube v3.1.0 nightly 97 - Windows 11)

Ex song tried : https://open.spotify.com/track/6ZLGthToczpvnL5Eoy6yrY

logs:

```
------- DEVICE INFO -------
computerName: pc37
numberOfCores: 16
systemMemoryInMegabytes: 32768
------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: nightly.97
packageName: spotube
---------- ERROR ----------
[SponsorBlock] no skip segments found for XI0vVvxq9rY
https://sponsor.ajay.app/api/skipSegments?videoID=XI0vVvxq9rY&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip
------- STACK TRACE -------
#0      ProxyPlaylistNotifier.getAndCacheSkipSegments (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:539)
<asynchronous suspension>
#1      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:171)
<asynchronous suspension>
------- CUSTOM INFO -------
```

**Comment by Emilv2** [comment]
I also have the same issue with the latest nightly on Android.

(I can't see any logs, is that another bug I should report?)

**Comment by KRTirtho** [comment]
> (I can't see any logs, is that another bug I should report?)
No it's not a bug. It's just in the "Settings" > "Logs" :smile:

**Comment by Emilv2** [comment]
That's what I mean, settings -> logs is empty 
![Screenshot_2023-08-08-11-19-24-60_1c96baa6fc3a4338d23fd334c3c04599](https://github.com/KRTirtho/spotube/assets/15071778/70aeb125-3808-4bd1-a932-14aa9dd6771f)

**Comment by KRTirtho** [comment]
Means you don't have any error logs or the logs are huge and taking time to load

**Comment by KRTirtho** [comment]
@xididri that same song loads fine for me. (Nice song btw. I never heard of Donna. Might start listen to her)
![image](https://github.com/KRTirtho/spotube/assets/61944859/824bb89c-55d6-40db-929a-744b370e360f)

**Comment by hanweikung** [comment]
The nightly build (AppImage) manages to continue playback after the songs that previously caused v.3.0.1 to pause. However, the nightly seemed always stuck at the end of the current song when the next song is this one in particular: https://open.spotify.com/track/4Ah5mAqvkmw5Hz2n6g5l0k

Messages from the command line: 
```bash
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubL4udSS/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
flutter: PostgrestException(message: duplicate key value violates unique constraint "tracks_spotify_id_idx", code: 23505, details: Conflict, hint: null)
flutter: #0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:345)
flutter: #1      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:202)
flutter: <asynchronous suspension>
flutter: #2      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:422)
flutter: <asynchronous suspension>
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubL4udSS/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /tmp/.mount_SpotubL4udSS/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
method call SetContextMenu
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)
ALSA lib conf.c:4623:(snd_config_update_r) hooks failed, removing configuration
```
Any clues?

**Comment by KRTirtho** [comment]
> ALSA lib conf.c:4002:(snd_config_hooks_call) Cannot open shared library (null) (/usr/lib/x86_64-linux-gnu/alsa-lib/usr/lib/libasound.so.2: cannot open shared object file: No such file or directory)

Uhm this doesn't seem right. Is your audio working properly in other apps?

**Comment by hanweikung** [comment]
Yes, my audio works fine in other apps (mpv, Spotify)

Does my .spotube_logs give any clues?

```bash
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-08 22:25:43.330109

------- DEVICE INFO -------
name: Ubuntu
version: 22.04.2 LTS (Jammy Jellyfish)
id: ubuntu
idLike: [debian]
versionCodename: jammy
versionId: 22.04
prettyName: Ubuntu 22.04.2 LTS
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.0.1
appName: spotube
buildNumber: nightly.97
packageName: spotube

---------- ERROR ----------
OAuth authorization error (invalid_token): The access token expired.

------- STACK TRACE -------
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:173)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:206)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:172)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```

**Comment by bel57** [comment]
Hello, I just discovered Spotube. It's a nice app but the playback is faulty.
As said here, most of the times it stops at the end of the song and doesn't play the next track.
**And that applies to local files too.** This time it's trying to play next song but there is no information in the now playing area:
![image](https://github.com/KRTirtho/spotube/assets/10614811/d6d4fc41-c4ff-407f-aab2-6a94aa69e6a9)

`------- DEVICE INFO -------
computerName: computer
numberOfCores: 16
systemMemoryInMegabytes: 16384
------- APP INFO -------
environment: release
version: 3.0.1
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
FormatException: Unexpected character (at character 1)
Too many requests
^
------- STACK TRACE -------
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleErrors (package:spotify/src/spotify_base.dart:226)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:206)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:172)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:236)
<asynchronous suspension>
#10     PlaylistQueries.featured.<anonymous closure> (package:spotube/services/queries/playlist.dart:181)
<asynchronous suspension>
#11     Retryer.retryOperation (package:fl_query/src/core/mixins/retryer.dart:16)
<asynchronous suspension>
#12     CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425)
<asynchronous suspension>
------- CUSTOM INFO -------`

**Comment by xididri** [comment]
I actually still have the bug with TSpotube v3.1.0 nightly 97 (Windows 11) but less often I think.

Logs:

```
------- DEVICE INFO -------
computerName: pc37
numberOfCores: 16
systemMemoryInMegabytes: 32768
------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: nightly.97
packageName: spotube
---------- ERROR ----------
[SponsorBlock] no skip segments found for rGarbUR6lCQ
https://sponsor.ajay.app/api/skipSegments?videoID=rGarbUR6lCQ&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip
------- STACK TRACE -------
#0      ProxyPlaylistNotifier.getAndCacheSkipSegments (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:539)
<asynchronous suspension>
#1      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:171)
<asynchronous suspension>
------- CUSTOM INFO -------
```

**Comment by saezhe** [comment]
im having the same problem with android installed from fdroid; it has happened both in a low internet environment and high internet environment.

```
------- DEVICE INFO -------
id: TP1A.220624.014
board: kona
bootloader: G781U1UESCGWFC
brand: samsung
device: r8q
display: TP1A.220624.014.G781U1UESCGWFC
fingerprint: samsung/r8quex/r8q:13/TP1A.220624.014/G781U1UESCGWFC:user/release-keys
hardware: qcom
host: 21DK7913
isPhysicalDevice: true
manufacturer: samsung
model: SM-G781U1
product: r8quex
tags: release-keys
type: user
versionBaseOs: samsung/r8quex/r8q:13/TP1A.220624.014/G781U1UEUBGWFA:user/release-keys
versionCodename: REL
versionIncremental: G781U1UESCGWFC
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-07-01
------- APP INFO -------
environment: release
version: 3.0.1
appName: Spotube
buildNumber: 20
packageName: oss.krtirtho.spotube
---------- ERROR ----------
Error Code: 500
Server error.
------- STACK TRACE -------
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 9112, tid: 9138, name 1.ui
os: android arch: arm64 comp: yes sim: no
build_id: '349b90037cce98d6af40333a629590c2'
isolate_dso_base: 72e0602000, vm_dso_base: 72e0602000
isolate_instructions: 72e08afd00, vm_instructions: 72e08aa000
    #00 abs 00000072e0d3091f virt 000000000072e91f _kDartIsolateSnapshotInstructions+0x480c1f
    #01 abs 00000072e0f76d5b virt 0000000000974d5b _kDartIsolateSnapshotInstructions+0x6c705b
    #02 abs 00000072e0ec825f virt 00000000008c625f _kDartIsolateSnapshotInstructions+0x61855f
    #03 abs 00000072e08c9c17 virt 00000000002c7c17 _kDartIsolateSnapshotInstructions+0x19f17
    #04 abs 00000072e0ee3f5f virt 00000000008e1f5f _kDartIsolateSnapshotInstructions+0x63425f
    #05 abs 00000072e08c5b63 virt 00000000002c3b63 _kDartIsolateSnapshotInstructions+0x15e63
    #06 abs 00000072e08c6d3b virt 00000000002c4d3b _kDartIsolateSnapshotInstructions+0x1703b
    #07 abs 00000072e0ec8843 virt 00000000008c6843 _kDartIsolateSnapshotInstructions+0x618b43
    #08 abs 00000072e0ec825f virt 00000000008c625f _kDartIsolateSnapshotInstructions+0x61855f
    #09 abs 00000072e08c9c17 virt 00000000002c7c17 _kDartIsolateSnapshotInstructions+0x19f17
    #10 abs 00000072e0ee3f5f virt 00000000008e1f5f _kDartIsolateSnapshotInstructions+0x63425f
    #11 abs 00000072e08c5b63 virt 00000000002c3b63 _kDartIsolateSnapshotInstructions+0x15e63
    #12 abs 00000072e08c6d3b virt 00000000002c4d3b _kDartIsolateSnapshotInstructions+0x1703b
    #13 abs 00000072e0ec870b virt 00000000008c670b _kDartIsolateSnapshotInstructions+0x618a0b
    #14 abs 00000072e0ec825f virt 00000000008c625f _kDartIsolateSnapshotInstructions+0x61855f
    #15 abs 00000072e08c9c17 virt 00000000002c7c17 _kDartIsolateSnapshotInstructions+0x19f17
    #16 abs 00000072e0ee3f5f virt 00000000008e1f5f _kDartIsolateSnapshotInstructions+0x63425f
    #17 abs 00000072e08c5b63 virt 00000000002c3b63 _kDartIsolateSnapshotInstructions+0x15e63
    #18 abs 00000072e08c6d3b virt 00000000002c4d3b _kDartIsolateSnapshotInstructions+0x1703b
    #19 abs 00000072e08c6ca7 virt 00000000002c4ca7 _kDartIsolateSnapshotInstructions+0x16fa7
    #20 abs 00000072e08c65b3 virt 00000000002c45b3 _kDartIsolateSnapshotInstructions+0x168b3
    #21 abs 00000072e0ee28c3 virt 00000000008e08c3 _kDartIsolateSnapshotInstructions+0x632bc3
    #22 abs 00000072e08c6523 virt 00000000002c4523 _kDartIsolateSnapshotInstructions+0x16823
------- CUSTOM INFO -------
```

**Comment by hanweikung** [comment]
> The playback has improved on v3.1.0 (latest) Please check & if fixed close this issue

Thank you for the update. Still I found Spotube stopped at the end of this song https://open.spotify.com/track/2YmIcPF20FEaQd8qwTK8zm

Could you check? I am using Ubuntu 22.04, and here is my log:

```bash
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-24 22:45:32.002371

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: 21
packageName: spotube

---------- ERROR ----------
PathNotFoundException: Cannot open file, path = '/home/hanwei/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#5      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#6      GSettings.get (package:gsettings/src/gsettings.dart:117)
<asynchronous suspension>
#7      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-24 22:45:34.258706

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: 21
packageName: spotube

---------- ERROR ----------
[SponsorBlock] no skip segments found for -d7J_QVX2U4
https://sponsor.ajay.app/api/skipSegments?videoID=-d7J_QVX2U4&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip

------- STACK TRACE -------
#0      ProxyPlaylistNotifier.getAndCacheSkipSegments (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:544)
<asynchronous suspension>
#1      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:171)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```

**Comment by hanweikung** [comment]
> @hanweikung can you provide the Playlist link?

Yes, please try this playlist https://open.spotify.com/playlist/3SnsCf1sbgXO9LvbvZC11N?si=b392f47a490846ee

Spotube stopped at the end of the first song. I suspect it was the next song causing the problem, not the current one.

Here is my log:

```bash
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-25 11:07:16.983988

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: 21
packageName: spotube

---------- ERROR ----------
PathNotFoundException: Cannot open file, path = '/home/hanwei/.var/app/com.github.KRTirtho.Spotube/config/dconf/user' (OS Error: No such file or directory, errno = 2)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:82)
<asynchronous suspension>
#5      GSettingsDConfBackend.get (package:gsettings/src/gsettings_dconf_backend.dart:23)
<asynchronous suspension>
#6      GSettings.get (package:gsettings/src/gsettings.dart:117)
<asynchronous suspension>
#7      getTheme (package:titlebar_buttons/src/get_theme.dart:12)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER LOG ==============================
Crash occurred on 2023-08-25 11:07:18.848667

------- DEVICE INFO -------
name: GNOME
version: 44 (Flatpak runtime)
id: org.gnome.Platform
idLike: null
versionCodename: null
versionId: 44
prettyName: GNOME 44 (Flatpak runtime)
buildId: null
variant: null
variantId: null
machineId: 50601393417c4eee9ce314c370032735

------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: 21
packageName: spotube

---------- ERROR ----------
[SponsorBlock] no skip segments found for -G2UmMbC5Bc
https://sponsor.ajay.app/api/skipSegments?videoID=-G2UmMbC5Bc&category=sponsor&category=selfpromo&category=interaction&category=intro&category=outro&category=music_offtopic&actionType=skip

------- STACK TRACE -------
#0      ProxyPlaylistNotifier.getAndCacheSkipSegments (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:544)
<asynchronous suspension>
#1      new ProxyPlaylistNotifier.<anonymous closure>.<anonymous closure> (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:171)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
```
