### ISSUE TITLE
Can't install on Fedora 38

### ISSUE THREAD

**Issue by xiaozhangup** [KRTirtho/spotube#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i use dnf to install rpm package on my fedora pc, it notice me 

`- nothing provides libmpv.so.1()(64bit) needed by spotube-3.0.1+20-20.x86_64 from @commandline
`

### Expected Behavior

Install it normally

### Steps to reproduce

1. Download
2. Use dnf install to install the program

### Operating System

Fedora 38

### Spotube version

3.0.1

### Installation source

GitHub Releases (Binary)

**Comment by RTTEXFile** [comment]
Do you have the `mpv` package installed on your system?

**Comment by xiaozhangup** [comment]
> Do you have the `mpv` package installed on your system?

I tried installing the mpv software package, but I still get this error message.

**Comment by RTTEXFile** [comment]
What does `ldconfig -p | grep libmpv` output?

**Comment by xiaozhangup** [comment]
> 

![图片](https://github.com/KRTirtho/spotube/assets/68374769/8732ed04-911e-46d1-bad0-0d70d9eed8c6)

**Comment by xiaozhangup** [comment]
> What does `ldconfig -p | grep libmpv` output?

![图片](https://github.com/KRTirtho/spotube/assets/68374769/e8d98761-14d6-4e9d-a560-9a5bd7ae9d1e)

**Comment by RTTEXFile** [comment]
Do you have `mpv-libs` installed? If not, try installing it and running spotube again.

**Comment by xiaozhangup** [comment]
> Do you have `mpv-libs` installed? If not, try installing it and running spotube again.

Still can't install, and if i use appimage to run,it shows:
`[xiaozhangup@xiaozhangup 桌面]$ ./Spotube-linux-x86_64.AppImage 
package:media_kit_libs_linux registered.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/libmpv/core/native_library.dart:63)
#1      ensureInitialized (package:media_kit/src/libmpv/entry_point.dart:14)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:33)
#3      main (package:spotube/main.dart:87)
<asynchronous suspension>
`

**Comment by RTTEXFile** [comment]
You **can't** install `mpv-libs`? What about `mpv-devel`?

**Comment by xiaozhangup** [comment]
> 

That's my install command
![图片](https://github.com/KRTirtho/spotube/assets/68374769/57aa93a5-08a6-4eee-9195-3b7e594a1729)

If i install mpv-devel, it will be:
![图片](https://github.com/KRTirtho/spotube/assets/68374769/d362d99a-2ca7-45b2-a13e-f20eb85f3ad5)

**Comment by RTTEXFile** [comment]
Is your AppImage the [latest version](https://github.com/KRTirtho/spotube/releases/tag/v3.0.1)?

**Comment by xiaozhangup** [comment]
> Is your AppImage the [latest version](https://github.com/KRTirtho/spotube/releases/tag/v3.0.1)?

yes

**Comment by RTTEXFile** [comment]
I have no more suggestions except the dangerous `sudo ln -rsv /lib64/libmpv.so.2 /lib64/libmpv.so.1`.

**Comment by xiaozhangup** [comment]
> I have no more suggestions except the dangerous `sudo ln -rsv /lib64/libmpv.so.2 /lib64/libmpv.so.1`.

So, can't it be installed directly on Fedora? Can this issue be resolved in future updates?

**Comment by KRTirtho** [comment]
@xiaozhangup please use Flatpak version for now

**Comment by xiaozhangup** [comment]
> @xiaozhangup please use Flatpak version for now

The Flatpak version of the tray has an issue where the tray icon cannot be displayed correctly on Gnome, instead showing "..."

**Comment by RTTEXFile** [comment]
> I have no more suggestions except the dangerous `sudo ln -rsv /lib64/libmpv.so.2 /lib64/libmpv.so.1`.

Did this work?

**Comment by xiaozhangup** [comment]
> > I have no more suggestions except the dangerous `sudo ln -rsv /lib64/libmpv.so.2 /lib64/libmpv.so.1`.
> 
> Did this work?

no

**Comment by KRTirtho** [comment]
> The Flatpak version of the tray has an issue where the tray icon cannot be displayed correctly on Gnome, instead showing "..."

The flatpak sandboxing is messing with icon path thus this issue occurs, I'm trying to find a solution

**Comment by KRTirtho** [comment]
Keep an eye on https://github.com/KRTirtho/spotube/issues/541 for this

**Comment by piko-piko** [comment]
Same issue on Artix here. Using appimage, i have mpv installed. `libmpv.so libmpv.so.2 libmpv.so.2.1.0` are present in /lib64 and /usr/lib/, `sudo ln -rsv /lib64/libmpv.so.2 /lib64/libmpv.so.1` did not help

**Comment by rayenghanmi22** [comment]
Facing the same problem on my Fedora 38 as well.
Any solution?

**Comment by xiaozhangup** [comment]
> Facing the same problem on my Fedora 38 as well. Any solution?

use flatpak

**Comment by GoldenReverie** [comment]
I can also confirm that i can only use the flatpak to install on fedora 38 currently. Even using Yum yields no results. "libmpv.so.1()(64bit)" appears to be a misnamed or unique version of the mpv package?

**Comment by servusdei2018** [comment]
@xiaozhangup 
CC: @KRTirtho @rayenghanmi 

Flutter's AppImage generation tool, used by Spotube, has a poorly configured AppRun script which sets `LD_LIBRARY_PATH` to `usr/lib`. On most 64-bit systems, mpv is being installed into `usr/lib64`. Until this oversight is fixed upstream, you will have to modify the AppImage manually. Please follow the steps mentioned here: https://github.com/KRTirtho/spotube/issues/643#issuecomment-1686315554

**Comment by soulis-1256** [comment]
I'm sorry, but isn't the problem that Fedora 38's mpv-libs x86_64 package provides a newer version of the required shared library? (version 2 instead of 1). Given that, wouldn't you need to try to build Spotube using the newer version of the lib and then split the release for rpm into fedora 38 and anything older than 38?

**Comment by tav1nald3rs0n** [comment]
> @xiaozhangup CC: @KRTirtho @rayenghanmi
> 
> Flutter's AppImage generation tool, used by Spotube, has a poorly configured AppRun script which sets `LD_LIBRARY_PATH` to `usr/lib`. On most 64-bit systems, mpv is being installed into `usr/lib64`. Until this oversight is fixed upstream, you will have to modify the AppImage manually. Please follow the steps mentioned here: [#643 (comment)](https://github.com/KRTirtho/spotube/issues/643#issuecomment-1686315554)
> 
> Edit: This issue has been generalized and filed upstream at [leanflutter/flutter_distributor#139](https://github.com/leanflutter/flutter_distributor/issues/139)

Do you understand what relative path and absolute path means?
`LD_LIBRARY_PATH` points to the bundled libmpv which should not have a problem at the first place.

**Comment by servusdei2018** [comment]
> `LD_LIBRARY_PATH` points to the bundled libmpv which should not have a problem at the first place.

No, `LD_LIBRARY_PATH` is pointing to a nonexistant folder on affected systems.

**Comment by brvn0** [comment]
Problem - as expected - is also occurring with Fedora 39

**Comment by Mubelotix** [comment]
Same problem on Ubuntu 23.10

**Comment by fabmazz** [comment]
Same problem here in Fedora 40, can't install because 
```
nothing provides libmpv.so.1()(64bit) needed by spotube-3.7.0+31-31.x86_64 from @commandline
```
The package `mpv-libs` provides `libmpv.so.2()(64bit)`. https://packages.fedoraproject.org/pkgs/mpv/mpv-libs/fedora-40.html

Does the package really need a specific version of the library?

**Comment by Mubelotix** [comment]
I'm not really sure that's the problem as creating a symlink of libmpv.so.1 to libmpv.so.2 didn't change anything. But I might be wrong

**Comment by Morgan-DCL** [comment]
Nop, symlink doesn't work either. Can't get trough install. Tried Flatpack, same issues as #1564

**Comment by fabiuz** [comment]
I use Fedora 38, this problem occurred here too.
After several analyses, I discovered how to work around this problem, see: https://github.com/KRTirtho/spotube/issues/1931.

**Comment by universish** [comment]
is not feodra. it is fedora. please correct the title. thanks

**Comment by KRTirtho** [comment]
Please use the Flatpak version. RPM support is discontinued
