### ISSUE TITLE
Windows 10 Download will not work on specific songs

### ISSUE THREAD

**Issue by Verizane** [KRTirtho/spotube#644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Download usually works, but on some tracks I get the following errors:

------- DEVICE INFO -------
computerName: 
numberOfCores: 16
systemMemoryInMegabytes: 32768
------- APP INFO -------
environment: release
version: 3.1.0
appName: spotube
buildNumber: 
packageName: spotube
---------- ERROR ----------
FileSystemException: Cannot create file, path = 'C:\Users\xxxxx\Downloads\Spotube\Song of Storms (from "The Legend of Zelda: Ocarina of Time") - Epic Version - L'Orchestra Cinematique, Alala.m4a.partial.temp0' (OS Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
, errno = 123)
------- STACK TRACE -------
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.createSync (dart:io/file_impl.dart:306)
#2      DioForNative.download (package:dio/src/dio/dio_for_native.dart:86)
<asynchronous suspension>
#3      ChunkDownload.chunkedDownload.downloadChunk (package:spotube/services/download_manager/chunked_download.dart:44)
<asynchronous suspension>
#4      ChunkDownload.chunkedDownload (package:spotube/services/download_manager/chunked_download.dart:77)
<asynchronous suspension>
#5      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:116)
<asynchronous suspension>
#6      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:393)
<asynchronous suspension>
------- CUSTOM INFO -------

### Expected Behavior

It should have downloaded correctly, but the name seems to interfere.

### Steps to reproduce

1. Installed Spotube
2. Opened it
3. Played some Songs, click on download, tried to download from playlist, tried to download when first playing etc.

### Operating System

Windows 10

### Spotube version

v3.1.0

### Installation source

GitHub Releases (Binary)

**Comment by Verizane** [comment]
Ah of course, quotes like "" are not allowed, i just tried via filesystem!

**Comment by KRTirtho** [comment]
Wow that's good catch. I didn't even know quotes were allowed on Spotify titles. We've to make sure to clean up the filename before saving on the next release.

**Comment by KRTirtho** [comment]
Fixed in v3.1.1

**Comment by h3oCharles** [comment]
i was about to open an issue, but found this, so here goes
version 3.9.0 from stable channel on windows from website, I get similar logs when trying to play a song that has quote marks in metadata

* Camellia, nomico - Bad Apple!! feat.nomico (Camellia's "Bad Psy" Remix) https://open.spotify.com/track/3OwSNk7BVwdCYivLzAso7b
* DM DOKURO - SAVE (Encore) ("Last Goodbye" from "Undertale") https://open.spotify.com/track/7foD0ypyQADVkaA1cXD0LW
* Arcade Player - Constant Moderato (From "Blue Archive") https://open.spotify.com/track/6nYTwJDxxcKSYjbD8YpA9C

<details>
<summary>Logs</summary>

```
[2024-12-30 00:34:02.504656]---------------------
FileSystemException: Cannot create file, path = 'C:\Users\karol\AppData\Local\oss.krtirtho\spotube\cached_tracks\Bad Apple!! feat.nomico (Camellia's "Bad Psy" Remix) - Camellia, nomico (x8t4J-9YSdw).weba.part' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.create.<anonymous closure> (dart:io/file_impl.dart:286)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      ServerPlaybackRoutes.streamTrack (package:spotube/provider/server/routes/playback.dart:126)
<asynchronous suspension>
#4      ServerPlaybackRoutes.getStreamTrackId (package:spotube/provider/server/routes/playback.dart:179)
<asynchronous suspension>
#5      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:109)
<asynchronous suspension>
#6      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#7      Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#8      handleRequest (package:shelf/shelf_io.dart:138)
<asynchronous suspension>

[2024-12-30 00:46:33.535616]---------------------
FileSystemException: Cannot create file, path = 'C:\Users\karol\AppData\Local\oss.krtirtho\spotube\cached_tracks\SAVE (Encore) ("Last Goodbye" from "Undertale") - DM DOKURO (ssyhcOhyesw).weba.part' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.create.<anonymous closure> (dart:io/file_impl.dart:286)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      ServerPlaybackRoutes.streamTrack (package:spotube/provider/server/routes/playback.dart:126)
<asynchronous suspension>
#4      ServerPlaybackRoutes.getStreamTrackId (package:spotube/provider/server/routes/playback.dart:179)
<asynchronous suspension>
#5      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:109)
<asynchronous suspension>
#6      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#7      Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#8      handleRequest (package:shelf/shelf_io.dart:138)
<asynchronous suspension>

[2024-12-30 00:49:38.947757]---------------------
FileSystemException: Cannot create file, path = 'C:\Users\karol\AppData\Local\oss.krtirtho\spotube\cached_tracks\Constant Moderato (From "Blue Archive") - Arcade Player (SHkF48SgiSA).weba.part' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.create.<anonymous closure> (dart:io/file_impl.dart:286)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      ServerPlaybackRoutes.streamTrack (package:spotube/provider/server/routes/playback.dart:126)
<asynchronous suspension>
#4      ServerPlaybackRoutes.getStreamTrackId (package:spotube/provider/server/routes/playback.dart:179)
<asynchronous suspension>
#5      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:109)
<asynchronous suspension>
#6      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#7      Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#8      handleRequest (package:shelf/shelf_io.dart:138)
<asynchronous suspension>
```

</details>
