### ISSUE TITLE
Can't create new playlist

### ISSUE THREAD

**Issue by Domipoke** [KRTirtho/spotube#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

------- DEVICE INFO -------
id: TP1A.220624.014
board: viva
bootloader: unknown
brand: Redmi
device: viva
display: TP1A.220624.014
fingerprint: Redmi/viva_eea/viva:13/TP1A.220624.014/V14.0.1.0.TGDEUXM:user/release-keys
hardware: mt6781
host: pangu-build-component-system-85668-krq9n-225d4-f7p35
isPhysicalDevice: true
manufacturer: Xiaomi
model: 2201116TG
product: viva_eea
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.1.0.TGDEUXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-04-01
------- APP INFO -------
environment: release
version: 3.1.1
appName: Spotube
buildNumber: 23
packageName: oss.krtirtho.spotube
---------- ERROR ----------
RangeError (index): Invalid value: Not in inclusive range 0..50: 51
------- STACK TRACE -------
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      DiffUtils.levEditDistance (package:fuzzywuzzy/diffutils/diff_utils.dart:600)
#2      DiffUtils.getRatio (package:fuzzywuzzy/diffutils/diff_utils.dart:732)
#3      SimpleRatio.apply (package:fuzzywuzzy/ratios/simple_ratio.dart:7)
#4      ratio (package:fuzzywuzzy/fuzzywuzzy.dart:14)
#5      WeightedRatio.apply (package:fuzzywuzzy/algorithms/weighted_ratio.dart:26)
#6      weightedRatio (package:fuzzywuzzy/fuzzywuzzy.dart:60)
#7      UserPlaylists.build.<anonymous closure>.<anonymous closure> (package:spotube/components/library/user_playlists.dart:65)
#8      MappedIterable.elementAt (dart:_internal/iterable.dart:375)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#12     new List.of (dart:core-patch/array_patch.dart:47)
#13     IterableExtension.sorted (package:collection/src/iterable_extensions.dart:59)
#14     UserPlaylists.build.<anonymous closure> (package:spotube/components/library/user_playlists.dart:66)
#15     _MemoizedHookState.value (package:flutter_hooks/src/primitives.dart:82)
#16     _MemoizedHookState.build (package:flutter_hooks/src/primitives.dart)
#17     HookElement._use (package:flutter_hooks/src/framework.dart:484)
#18     Hook.use (package:flutter_hooks/src/framework.dart:139)
#19     use (package:flutter_hooks/src/framework.dart:18)
#20     useMemoized (package:flutter_hooks/src/primitives.dart:61)
#21     UserPlaylists.build (package:spotube/components/library/user_playlists.dart:53)
#22     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:477)
#23     StatefulElement.build (package:flutter/src/widgets/framework.dart:5198)
#24     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:538)
#25     HookElement.build (package:flutter_hooks/src/framework.dart:436)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
#27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
#30     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
#31     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
#32     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
#33     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
#34     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
#35     _invoke (dart:ui/hooks.dart:142)
#36     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
#37     _drawFrame (dart:ui/hooks.dart:112)
------- CUSTOM INFO -------

### Expected Behavior

Creare a playlist

### Steps to reproduce

Clicked on + button to create new playlist and nothing happens

### Operating System

Android

### Spotube version

V3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), F-Droid (Android)

**Comment by Domipoke** [comment]
Update: I close app and open it again and playlist was created but if I want to create a new one I have to create - > close app - > open again
