### ISSUE TITLE
Crashes while loading on Android 14

### ISSUE THREAD

**Issue by Vitalii-code** [KRTirtho/spotube#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to launch the application but it's stuck on loading stage.

### Expected Behavior

It should launch and work

### Steps to reproduce

1. I opened the app
2. Crush

### Operating System

Android 14 pixel 6a

### Spotube version

v3.2.0

### Installation source

F-Droid (Android)

### Additional information

After rebooting my phone the issue is usually gone

**Comment by KRTirtho** [comment]
Android 14 is not tested so can't guarentee. Can you provide the logs?

**Comment by Vitalya-code** [comment]
> Android 14 is not tested so can't guarentee. Can you provide the logs?

sure, but how?

**Comment by KRTirtho** [comment]
Just go to "Settings" > "Logs" and copy using the top most copy button

**Comment by Vitalya-code** [comment]
```
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
id: UP1A.231005.007
board: bluejay
bootloader: bluejay-1.3-10674934
brand: google
device: bluejay
display: UP1A.231005.007
fingerprint: google/bluejay/bluejay:14/UP1A.231005.007/10754064:user/release-keys
hardware: bluejay
host: abfarm-release-rbe-64-2004-0089
isPhysicalDevice: true
manufacturer: Google
model: Pixel 6a
product: bluejay
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10754064
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2023-10-05
------- APP INFO -------
environment: release
version: 3.2.0
appName: Spotube
buildNumber: 25
packageName: oss.krtirtho.spotube
---------- ERROR ----------
Bad state: RenderBox was not laid out: RenderFlex#cae94
------- STACK TRACE -------
#0      RenderBox.size (package:flutter/src/rendering/box.dart:1987)
#1      PlaybuttonCard.build (package:spotube/components/shared/playbutton_card.dart:69)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:5367)
#3      HookElement.build (package:flutter_hooks/src/framework.dart:436)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#6      StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#7      HookElement.update (package:flutter_hooks/src/framework.dart:398)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#13     HookElement.update (package:flutter_hooks/src/framework.dart:398)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#15     Element.updateChildren (package:flutter/src/widgets/framework.dart:3834)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#66     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#70     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#75     HookElement.update (package:flutter_hooks/src/framework.dart:398)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#90     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#102    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#105    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#107    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#111    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#117    Element.updateChildren (package:flutter/src/widgets/framework.dart:3834)
#118    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#124    HookElement.update (package:flutter_hooks/src/framework.dart:398)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#126    Element.updateChildren (package:flutter/src/widgets/framework.dart:3834)
#127    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#131    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#137    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#145    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#147    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#150    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#154    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#158    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#168    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#171    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#173    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#177    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#187    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#191    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#193    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#195    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#197    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#199    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#201    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#204    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#206    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#208    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#214    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#218    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#223    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#227    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#230    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#231    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#235    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#236    HookElement.update (package:flutter_hooks/src/framework.dart:398)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#240    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#241    HookElement.update (package:flutter_hooks/src/framework.dart:398)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#245    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#249    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#253    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#256    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#257    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#259    Element.updateChildren (package:flutter/src/widgets/framework.dart:3834)
#260    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#264    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#269    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#272    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#273    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#274    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#275    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#277    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#278    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#279    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#281    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#282    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#283    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#284    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#285    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#289    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#291    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#292    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#293    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#294    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#296    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#297    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#298    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#299    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#300    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#301    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#302    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#303    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#304    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#305    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#306    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#307    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#308    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#309    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#310    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#311    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#312    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#313    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#314    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#315    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#316    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#318    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#320    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#321    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#322    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#323    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#324    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#325    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#326    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#327    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485)
#328    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#329    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#330    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#331    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#333    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441)
#334    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#335    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#336    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#337    StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#338    Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#340    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
#341    Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#342    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779)
#343    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153)
#344    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604)
#345    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059)
#346    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604)
#347    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#348    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313)
#349    RenderObject.layout (package:flutter/src/rendering/object.dart:2493)
#350    RenderBox.layout (package:flutter/src/rendering/box.dart:2382)
#351    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
#352    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056)
#353    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
#354    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:405)
#355    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332)
#356    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013)
#357    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494)
#358    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918)
#359    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360)
#360    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297)
#361    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#362    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085)
#363    _invoke (dart:ui/hooks.dart:170)
#364    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401)
#365    _drawFrame (dart:ui/hooks.dart:140)
------- CUSTOM INFO -------```
