### ISSUE TITLE
[Linux] After first launch Spotube only starts up to a transparent window

### ISSUE THREAD

**Issue by PureTryOut** [KRTirtho/spotube#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've installed Spotube from Flathub. The first time I launch the program it works just fine but the second time I do it opens up to just a transparent window (I only see the window borders). The logs report:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/bart/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.cache.queries.lock' (OS Error: Resource temporarily unavailable, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1022)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      QueryClient.initialize (package:fl_query/src/core/client.dart:529)
<asynchronous suspension>
#6      main (package:spotube/main.dart:68)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/bart/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.cache.queries.lock' (OS Error: Resource temporarily unavailable, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1022)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      QueryClient.initialize (package:fl_query/src/core/client.dart:529)
<asynchronous suspension>
#6      main (package:spotube/main.dart:68)
<asynchronous suspension>
```

### Expected Behavior

Spotube to always launch like it did the first time, without a transparent window.

### Steps to reproduce

1. Install from Flathub
2. Open the app once
3. Close the application
4. Open the app again

### Operating System

Linux

### Spotube version

3.2.0

### Installation source

Flathub (Flatpak)

**Comment by PureTryOut** [comment]
Ah, found the problem. Quitting the application doesn't actually quit it properly. There is still a "icon" in the system tray (using KDE Plasma). Well icon is not really accurate, it's just an empty spot, no icon is actually shown. But that is blocking the launching of the application. If I kill the still running application (sending SIGKILL) then I can launch it up fine again.

**Comment by KRTirtho** [comment]
Same as #768
