### ISSUE TITLE
Error Authentication Failure

### ISSUE THREAD

**Issue by Lostking24** [KRTirtho/spotube#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting this error when opening

ClientException with SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = open.spotify.com, port = 54372, uri=https://open.spotify.com/get_access_token? reason=transport&productType=web_player

### Expected Behavior

Music available

### Steps to reproduce

I opened the app

### Operating System

Android

### Spotube version

Android 14

### Installation source

F-Droid (Android)

**Comment by KRTirtho** [comment]
Can you try clearing data from App Info and trying re-login?

**Comment by Lostking24** [comment]
I've logged out and back on again and worked but not sure if this error can be fixed permanently or whether it's gonna happen every day or so

**Comment by rod93** [comment]
Same error for me

**Comment by hongsedaima** [comment]
> 您可以尝试清除应用程序信息中的数据并尝试重新登录吗？

问题依旧存在，我从Chrome退出、重新登录了Spotify，我打开或关闭VPN的全局模式，我卸载删除整个目录并重新安装……
无论做任何尝试，依旧是这个问题，并且，根据提示的信息完全不知道原因，无法采取任何有效措施来解决。

**Comment by qubaolai** [comment]
I'm having this problem too.

**Comment by topas-rec** [comment]
I see this on an arch linux system.
The system is on:
```
Name            : spotube
Version         : 3.8.3-1
```

(relevant parts of the) logs:
```
[2024-11-16 15:54:36.805913]---------------------
OAuth authorization error (invalid_client).
#0      _handleErrorResponse (package:oauth2/src/handle_access_token_response.dart:155)
#1      handleAccessTokenResponse (package:oauth2/src/handle_access_token_response.dart:41)
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:74)
<asynchronous suspension>

----------------------------------------
[2024-11-16 15:54:36.813188]---------------------
OAuth authorization error (invalid_client).
#0      _handleErrorResponse (package:oauth2/src/handle_access_token_response.dart:155)
#1      handleAccessTokenResponse (package:oauth2/src/handle_access_token_response.dart:41)
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:74)
<asynchronous suspension>

----------------------------------------
[2024-11-16 15:54:36.889028]---------------------
OAuth authorization error (invalid_client).
#0      _handleErrorResponse (package:oauth2/src/handle_access_token_response.dart:155)
#1      handleAccessTokenResponse (package:oauth2/src/handle_access_token_response.dart:41)
#2      clientCredentialsGrant (package:oauth2/src/client_credentials_grant.dart:74)
<asynchronous suspension>

----------------------------------------
[2024-11-16 15:54:45.922499]---------------------
Exception: [CustomSpotifyEndpoints.getView]: accessToken is empty
#0      CustomSpotifyEndpoints.getView (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:65)
#1      viewProvider.<anonymous closure> (package:spotube/provider/spotify/views/view.dart:13)
#2      AutoDisposeFamilyBase.call.<anonymous closure> (package:riverpod/src/framework/family.dart:199)
#3      FutureProvider._create (package:riverpod/src/future_provider/base.dart:65)
#4      FutureProviderElement.create.<anonymous closure> (package:riverpod/src/future_provider/base.dart:107)
#5      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:334)
#6      FutureHandlerProviderElementMixin._handleAsync (package:riverpod/src/async_notifier/base.dart:381)
#7      FutureHandlerProviderElementMixin.handleFuture (package:riverpod/src/async_notifier/base.dart:328)
#8      FutureProviderElement.create (package:riverpod/src/future_provider/base.dart:106)
#9      ProviderElementBase.buildState (package:riverpod/src/framework/element.dart:409)

[...]          <----- intentionally removed by me

#725    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#726    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#727    _rootRun (dart:async/zone.dart:1399)
#728    _CustomZone.run (dart:async/zone.dart:1301)
#729    _CustomZone.runGuarded (dart:async/zone.dart:1209)
#730    _invoke (dart:ui/hooks.dart:314)
#731    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#732    _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------
[2024-11-16 15:54:46.754925]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------

```
