### ISSUE TITLE
Offline Music Play Error

### ISSUE THREAD

**Issue by finey-dev** [KRTirtho/spotube#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i go offline i expect to play my downloaded songs/tracks but instead it loads infinitely and this error in my logs: 
---------- ERROR ----------
Invalid argument (value): Invalid object path: "/trackId/Shusha Nyavu - Christina Shusho"
------- STACK TRACE -------
#0      new DBusObjectPath (package:dbus/src/dbus_value.dart:450)
#1      Metadata.toValue (package:audio_service_mpris/metadata.dart:109)
#2      OrgMprisMediaPlayer2.metadata= (package:audio_service_mpris/mpris.dart:142)
#3      AudioServiceMpris.setMediaItem (package:audio_service_mpris/audio_service_mpris.dart:109)
#4      AudioService._observeMediaItem.<anonymous closure> (package:audio_service/audio_service.dart:1059)
<asynchronous suspension>
------- CUSTOM INFO -------

### Expected Behavior

I expect to be able to play my downloaded tracks immediately i go offline, not infinte loader...

### Steps to reproduce

1. Opened the app
2. Started playing music online
3. Downloaded several tracks
4. Wen't offline 
5.Then tried plaing my downloaded tracks

### Operating System

Linux & Windows

### Spotube version

3.3.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by Abhihihi** [comment]
Yes! Detecting that a device is offline needs to be handled more elegantly in the app! Even the Android app gives a pop up,bruh I know I'm offline. Now just use the feature that is present in the app, i.e. the downloaded songs, and play me some songs. I think that's the logical thing that should happen.
