### ISSUE TITLE
Blank screen right after logging into spotify in linux

### ISSUE THREAD

**Issue by Mikesco3** [KRTirtho/spotube#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## on Spotube v3.4.0
when I open spotube and enter my credentials for spotify (the sp_dc and sp_key) the screen goes blank.

![Peek 2023-12-30 23-43](https://github.com/KRTirtho/spotube/assets/13419518/6b694d95-8384-4d0c-9d1f-c36a56a81398)

### Expected Behavior

the normal behavior should be that I get the spotube screen ready to start searching and playing songs

### Steps to reproduce

1. I installed spotube from the aur 
 _(installed the required dependencies: `mpv, libappindicator-gtk3, libsecret, jsoncpp, libnotify, xdg-user-dirs`)_ <br>
2. Opened spotube (it came up ok)
3. Entered my spotify credentials from the cookie (sp_dc and sp_key)
4. then as soon as I confirm, the screen goes blank <br>
![image](https://github.com/KRTirtho/spotube/assets/13419518/f60ab0ea-d078-462f-8e1d-237e96fa4112) <br>
It doesn't matter if I kill the task and reopen, it goes back to the same blank screen
5. If I delete the config location <br>
`/home/myUserName/.local/share/spotube/` <br>
It goes back to first screen that launched before it went blank
___
6. I then proceeded to try to download the tar.gz straight from the github release asset, unpacked it and ran it (same behavior)

### Operating System

Linux Manjaro on XFCE4 (gtk using Xorg)

### Spotube version

v3.4.0

### Installation source

GitHub Releases (Binary)

#### v3.3.0 and nightly v3.1.2 - build 151 Login OK, but wont quit the tray Icon
1. I then downloaded the tar.gz for the **3.3.0** release and it runs OK... 
2. I can login to spotify Fine.
3. The only issue with it, is that when I close it, it goes to the tray Icon, 
4. but then I can't quit it from the tray Icon..
 I started it from the terminal to see the output and this will start to scroll by when I try to quit from the tray icon:
 ```
Attempt:11 waiting for isolate vm-isolate to check in
Attempt:11 waiting for isolate InitializerIsolate._mainloop to check in
Attempt:12 waiting for isolate vm-isolate to check in
Attempt:12 waiting for isolate InitializerIsolate._mainloop to check in
Attempt:13 waiting for isolate vm-isolate to check in
```
 ___
 Also the **nightly** tar.gz version have the same behavior as `v3.3.0` <br>

 **Version:** `v3.1.2` 
 **Build Number:** `nightly 151`

**Comment by Mikesco3** [comment]
just in case I also went and started spotube 3.4.0  from the terminal, and I get the blank screen, here is the output on the terminal:
___
```
[myUserName@t3600 spotube-linux-3.4.0-x86_64]$ ./spotube 

(process:275924): GLib-GObject-CRITICAL **: 22:33:49.435: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'

(spotube:275924): Gdk-CRITICAL **: 22:33:49.497: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: Configure AudioServiceLinux.
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /home/myUserName/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
flutter: setQueue() has not been implemented.
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
flutter: GetPosition(): 0:00:00.000000
method call SetContextMenu
flutter: MenuItem select menuId:1 menuItemId:7
```
___
but it at least quits fine from the tray Icon...

**Comment by Mikesco3** [comment]
### Update 
if I replace `/lib/libapp.so` with the one from v3.3.0 it runs OK and even closes fine...

**Comment by Mikesco3** [comment]
also I ran `ldd ./spotube` from `spotube-linux-3.4.0-x86_64`
and I get:
```
	linux-vdso.so.1 (0x00007fff7f52c000)
	libdart_discord_rpc_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libdart_discord_rpc_plugin.so (0x00007f81d9d12000)
	libfile_selector_linux_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libfile_selector_linux_plugin.so (0x00007f81d9d0b000)
	libflutter_secure_storage_linux_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libflutter_secure_storage_linux_plugin.so (0x00007f81d9ced000)
	libgtk_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libgtk_plugin.so (0x00007f81d9ce7000)
	liblocal_notifier_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/liblocal_notifier_plugin.so (0x00007f81d9cdf000)
	libmedia_kit_libs_linux_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libmedia_kit_libs_linux_plugin.so (0x00007f81d9cd8000)
	libscreen_retriever_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libscreen_retriever_plugin.so (0x00007f81d9cd2000)
	libsystem_theme_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libsystem_theme_plugin.so (0x00007f81d9ccc000)
	libsystem_tray_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libsystem_tray_plugin.so (0x00007f81d9cbf000)
	liburl_launcher_linux_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/liburl_launcher_linux_plugin.so (0x00007f81d9cb9000)
	libwindow_manager_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libwindow_manager_plugin.so (0x00007f81d9caa000)
	libwindow_size_plugin.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libwindow_size_plugin.so (0x00007f81d9ca3000)
	libflutter_linux_gtk.so => /home/mikesco3/Downloads/tempSpotube/spotube-linux-3.4.0-x86_64/./lib/libflutter_linux_gtk.so (0x00007f81d8e00000)
	libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f81d8600000)
	libgdk-3.so.0 => /usr/lib/libgdk-3.so.0 (0x00007f81d8506000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f81d9c5e000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f81d849c000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f81d838e000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f81d8dd8000)
	libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x00007f81d9c51000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f81d8255000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f81d820f000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f81d8036000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f81d7fd4000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f81d7e88000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f81d7c00000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f81d7b13000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f81d7aee000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f81d790c000)
	libsecret-1.so.0 => /usr/lib/libsecret-1.so.0 (0x00007f81d78ac000)
	libnotify.so.4 => /usr/lib/libnotify.so.4 (0x00007f81d789f000)
	libappindicator3.so.1 => /usr/lib/libappindicator3.so.1 (0x00007f81d788f000)
	libdbusmenu-glib.so.4 => /usr/lib/libdbusmenu-glib.so.4 (0x00007f81d7872000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f81d7e7f000)
	libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x00007f81d7741000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f81d76f2000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f81d76ed000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f81d9d71000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f81d76e6000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f81d76cf000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f81d76af000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f81d769b000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f81d7558000)
	libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x00007f81d751d000)
	libcloudproviders.so.0 => /usr/lib/libcloudproviders.so.0 (0x00007f81d7505000)
	libtracker-sparql-3.0.so.0 => /usr/lib/libtracker-sparql-3.0.so.0 (0x00007f81d7429000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f81d7421000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007f81d73d8000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f81d73c6000)
	libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007f81d73ba000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007f81d73b5000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f81d73a0000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f81d7394000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f81d738f000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f81d738a000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f81d737b000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f81d7376000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f81d736b000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f81d729d000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f81d727a000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f81d725e000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f81d7224000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f81d7217000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f81d71ec000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f81d71dd000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f81d71d8000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f81d7129000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f81d707c000)
	libtiff.so.6 => /usr/lib/libtiff.so.6 (0x00007f81d6fee000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f81d6f9e000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x00007f81d6f93000)
	libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007f81d6ef6000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f81d6dad000)
	libtss2-esys.so.0 => /usr/lib/libtss2-esys.so.0 (0x00007f81d6d10000)
	libtss2-mu.so.0 => /usr/lib/libtss2-mu.so.0 (0x00007f81d6cc0000)
	libtss2-rc.so.0 => /usr/lib/libtss2-rc.so.0 (0x00007f81d6cb6000)
	libtss2-tctildr.so.0 => /usr/lib/libtss2-tctildr.so.0 (0x00007f81d6cac000)
	libdbusmenu-gtk3.so.4 => /usr/lib/libdbusmenu-gtk3.so.4 (0x00007f81d6c96000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f81d6c6b000)
	libatspi.so.0 => /usr/lib/libatspi.so.0 (0x00007f81d6c31000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f81d6be0000)
	libjson-glib-1.0.so.0 => /usr/lib/libjson-glib-1.0.so.0 (0x00007f81d6bb6000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f81d6a4a000)
	libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007f81d68eb000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f81d68e2000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f81d68cf000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f81d68c0000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f81d68b9000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f81d68b1000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f81d67de000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f81d67ab000)
	libjbig.so.2.1 => /usr/lib/libjbig.so.2.1 (0x00007f81d679e000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f81d6760000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f81d673a000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f81d6200000)
	libtss2-sys.so.1 => /usr/lib/libtss2-sys.so.1 (0x00007f81d61d9000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f81d60e5000)
	libicuuc.so.74 => /usr/lib/libicuuc.so.74 (0x00007f81d5e00000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f81d60c2000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f81d60b6000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f81d6094000)
	libicudata.so.74 => /usr/lib/libicudata.so.74 (0x00007f81d4000000)
```
I seem to be missing 	`linux-vdso.so.1` 
I ran a search for it, but I don't seem to find anything with `linux-vdso.*`

**Comment by KRTirtho** [comment]
Can you check if Flatpak version works?

3.4.0 is not yet released but there's a test build for flatpak is available.

https://github.com/flathub/com.github.KRTirtho.Spotube/pull/48#issuecomment-1872679418

**Comment by hamkg** [comment]
Same experience as @Mikesco3 : screen goes blank (grey) after entering Spotify credentials. Runs OK after replacing /lib/libapp.so with the file frpn Spotube-3.3.0.

This on Linux (Slackware) and the .rpm package.

**Comment by Mark3xtrm** [comment]
Hi, @KRTirtho , thanks for this awesome app!

Same here on Mint Cinnamon using .deb.
3.3.0 used to work fine, but 3.4.0 is stuck on this blank screen after logged in with sp_dc and sp_key.
I rather use deb, not Flatpak

**Comment by jude7733** [comment]
**flatpak version - com.github.KRTirtho.Spotube/** v3.4.0
Fedora 39
Gnome 45

Resulted in blank screen with following output
```
$flatpak run com.github.KRTirtho.Spotube/

(process:2): GLib-GObject-CRITICAL **: 20:35:19.970: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'

(spotube:2): Gdk-CRITICAL **: 20:35:20.090: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: Configure AudioServiceLinux.
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call SetContextMenu
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
flutter: setQueue() has not been implemented.
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
flutter: GetPosition(): 0:00:00.000000
flutter: GetPosition(): 0:00:00.000000
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
sh: line 1: xdg-mime: command not found
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call DestroySystemTray
method call InitSystemTray
SystemTray::set_system_tray_info title: , icon_path: /app/spotube/data/flutter_assets/assets/spotube-logo.png, toolTip: (null)
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call CreateContextMenu
value_to_menu_item type:label, label:Show/Hide
value_to_menu_item type:label, label:Play/Pause
value_to_menu_item type:label, label:Next
value_to_menu_item type:label, label:Previous
value_to_menu_item type:label, label:Quit
method call SetContextMenu
flutter: Requested property Position from org.mpris.MediaPlayer2.Player
method call SetContextMenu
flutter: GetPosition(): 0:00:00.000000
method call SetContextMenu

```

_Note_
I can play previously played songs from notification

**Comment by baskinsy** [comment]
I have the same issue with the 3.4.0 rpm for Opensuse (latest Tumbleweed). Strangely, I have the issue with 3.3.0 flatpak also but the 3.3.0 rpm works fine.

**Comment by Icedtea1012** [comment]
I have the same issue I'm on pop os and both the .deb and flatpak have the same problem for me after i sign in.

**Comment by houssemko** [comment]
same problem on garuda with the aur problem

**Comment by houssemko** [comment]
how do I reset the app?

**Comment by Mikesco3** [comment]
> how do I reset the app?

to clear the cached login credentials I went to `/home/mikesco3/.local/share/spotube/` and deleted the content... 

then you can 
1. Download the v3.3.0 tar.gz file [spotube-linux-3.3.0-x86_64.tar.xz](https://github.com/KRTirtho/spotube/releases/download/v3.3.0/spotube-linux-3.3.0-x86_64.tar.xz) 
2. Extract the contents 
3. copy `libapp.so`  from `spotube-linux-3.3.0-x86_64/lib/`
4. paste it into the `lib` folder of the installed spotube 
   (in my distro of linux I was able to find the folder by finding where the /usr/bin/spotube symlink was pointing to:
   ```
  $ which spotube 
     /usr/bin/spotube
  $ ls -la /usr/bin/spotube
     lrwxrwxrwx 1 root root 30 Dec 30 20:21 /usr/bin/spotube -> /usr/share/spotube-bin/spotube
   ```
   so I pasted the `libapp.so` into  `/usr/share/spotube-bin/lib/`

**Comment by Mikesco3** [comment]
> Can you check if Flatpak version works?
> 
> 3.4.0 is not yet released in Flathub but there's a test build for flatpak is available.
> 
> [flathub/com.github.KRTirtho.Spotube#48 (comment)](https://github.com/flathub/com.github.KRTirtho.Spotube/pull/48#issuecomment-1872679418)

@KRTirtho I got the same blank screen when I downloaded the flatpak v 3.4.0 from your link

**Comment by taha-ghadirian** [comment]
Same issue on Arch linux, Sway Wayland, Spotube version: 3.4.0 installed from AUR (Yay)
Fixed via replacing libapp.so as mentioned in https://github.com/KRTirtho/spotube/issues/978#issuecomment-1873037178

**Comment by siliconsniffer** [comment]
> Can you check if Flatpak version works?
> 
> 3.4.0 is not yet released in Flathub but there's a test build for flatpak is available.
> 
> [flathub/com.github.KRTirtho.Spotube#48 (comment)](https://github.com/flathub/com.github.KRTirtho.Spotube/pull/48#issuecomment-1872679418)

I also opened an issue regarding this at: https://github.com/KRTirtho/spotube/issues/989

```shell
(process:2): GLib-GObject-CRITICAL **: 13:12:03.336: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
Gtk-Message: 13:12:03.368: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:12:03.369: Failed to load module "canberra-gtk-module"

(spotube:2): Gdk-CRITICAL **: 13:12:03.373: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/linus/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.skip_segments.v1.lock' (OS Error: Die Ressource ist zur Zeit nicht verfügbar, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      main (package:spotube/main.dart:102)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/linus/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.skip_segments.v1.lock' (OS Error: Die Ressource ist zur Zeit nicht verfügbar, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      main (package:spotube/main.dart:102)
<asynchronous suspension>


```
(OS Error: Die Ressource ist zur Zeit nicht verfügbar, errno = 11) = (OS Error: The resource is currently not available, errno = 11)

**Comment by KRTirtho** [comment]
Please re-install Spotube, the release has been updated with a fix. But no version was released, as it's happening only one platform.

> If you're on Arch Linux using yay or pamac first make sure to remove cache `yay -Sc` otherwise install will face integrity error

**Comment by siliconsniffer** [comment]
> Please re-install Spotube, the release has been updated with a fix. But no version was released, as it's happening only on one platform.
> 
> > If you're on Arch Linux using yay or pamac first make sure to remove cache `yay -Sc` otherwise install will face integrity error

Via Flatpak?

**Comment by TheUncleRemus** [comment]
> ### Update
> 
> if I replace `/lib/libapp.so` with the one from v3.3.0 it runs OK and even closes fine...

I tried this and the app works but this is not a solution is a workaround.

Regards

**Comment by hamkg** [comment]
Thanks a lot for the fix, @KRTirtho - I downloaded the updated .rpm version and, as usually, repacked it into a slackware .txz package. Everything runs just fine.

**Comment by KRTirtho** [comment]
> > Please re-install Spotube, the release has been updated with a fix. But no version was released, as it's happening only on one platform.
> > 
> > > If you're on Arch Linux using yay or pamac first make sure to remove cache `yay -Sc` otherwise install will face integrity error
> 
> Via Flatpak? Debian Packet from the website works perfectly! Thanks for the fix!

Flatpak should be available within dome hours.

**Comment by Mikesco3** [comment]
> > > Please re-install Spotube, the release has been updated with a fix. But no version was released, as it's happening only on one platform.
> > > > If you're on Arch Linux using yay or pamac first make sure to remove cache `yay -Sc` otherwise install will face integrity error
> > 
> > 
> > Via Flatpak? Debian Packet from the website works perfectly! Thanks for the fix!
> 
> Flatpak should be available within some hours.

@KRTirtho Flatpak worked amazing!!!

**Comment by Mikesco3** [comment]
@KRTirtho I just upgraded from the AUR and it works amazing!!

I think you have squashed this bug!

Phenomenal Work!

Happy New Year.... 

Thanks again!

**Comment by evdcush** [comment]
Is there any fix planned for the Flatpak?

I'm on `7.4.0` and I still cannot launch the app.

```
flatpak run com.github.KRTirtho.Spotube 

(process:2): GLib-GObject-CRITICAL **: 17:00:07.422: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
Gtk-Message: 17:00:07.445: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:00:07.446: Failed to load module "canberra-gtk-module"

(spotube:2): Gdk-CRITICAL **: 17:00:07.474: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (spotube:2): WARNING **: 17:00:07.479: Failed to start Flutter renderer: No available configurations for the given pixel format
package:media_kit_libs_linux registered.

** (spotube:2): WARNING **: 17:00:07.479: gtk.dart: failed to call method: No engine to send to
```

**Comment by KRTirtho** [comment]
Closing this as completed
